In [1]:
  !git clone https://github.com/mkobycheva/recommendation-system.git 2>/dev/null \
  || (cd recommendation-system && git pull)

%cd recommendation-system
!git checkout transformer && git pull
!pip install -r requirements.txt -q

import sys
sys.path.insert(0, '.')

from google.colab import drive
drive.mount('/content/drive')

Already up to date.
/content/recommendation-system
Already on 'transformer'
Your branch is up to date with 'origin/transformer'.
Already up to date.
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import os
import numpy as np
import pandas as pd

from src.evaluation.metrics import ndcg_at_k, recall_at_k, map_at_k

# Data preparation

In [3]:
DATA_DIR = '/content/drive/MyDrive/recsys-data'

books_train = pd.read_csv(f'{DATA_DIR}/books_train.csv')
books_valid = pd.read_csv(f'{DATA_DIR}/books_valid.csv')
books_test = pd.read_csv(f'{DATA_DIR}/books_test.csv')

movies_train = pd.read_csv(f'{DATA_DIR}/movies_train.csv')
movies_valid = pd.read_csv(f'{DATA_DIR}/movies_valid.csv')
movies_test = pd.read_csv(f'{DATA_DIR}/movies_test.csv')

In [4]:
from src.data.build_matrix import add_domain_item_ids
from sklearn.preprocessing import LabelEncoder

books_train = add_domain_item_ids(books_train, 'books')
books_valid = add_domain_item_ids(books_valid, 'books')
books_test  = add_domain_item_ids(books_test, 'books')

movies_train = add_domain_item_ids(movies_train, 'movies')
movies_valid = add_domain_item_ids(movies_valid, 'movies')
movies_test  = add_domain_item_ids(movies_test, 'movies')

train_df = pd.concat([books_train, movies_train], ignore_index=True)
valid_df = pd.concat([books_valid, movies_valid], ignore_index=True)
test_df  = pd.concat([books_test, movies_test], ignore_index=True)

# 5-core item filtering
# Only train_df decides which items "count" — valid/test must never leak info
# about which items are frequent, they can only inherit train's decision.
MIN_ITEM_FREQ = 5
item_counts_train = train_df['item_id'].value_counts()
frequent_items = set(item_counts_train[item_counts_train >= MIN_ITEM_FREQ].index)

print(f"Items before filtering: {train_df['item_id'].nunique()}")
print(f"Items after filtering (freq >= {MIN_ITEM_FREQ}): {len(frequent_items)}")

rows_before = {name: len(df) for name, df in [('train', train_df), ('valid', valid_df), ('test', test_df)]}

train_df = train_df[train_df['item_id'].isin(frequent_items)].reset_index(drop=True)
valid_df = valid_df[valid_df['item_id'].isin(frequent_items)].reset_index(drop=True)
test_df  = test_df[test_df['item_id'].isin(frequent_items)].reset_index(drop=True)

for name, df, before in [('train', train_df, rows_before['train']),
                          ('valid', valid_df, rows_before['valid']),
                          ('test', test_df, rows_before['test'])]:
    print(f"{name}: {before} -> {len(df)} rows ({100*len(df)/before:.1f}% kept)")

# --- Rebuild vocab on the FILTERED data only, so NUM_ITEMS actually shrinks ---
encoder = LabelEncoder()
encoder.fit(pd.concat([train_df['item_id'], valid_df['item_id'], test_df['item_id']]).unique())

NUM_ITEMS = len(encoder.classes_) + 1
print(f"NUM_ITEMS = {NUM_ITEMS}")

for df in (train_df, valid_df, test_df):
    df['item_idx'] = encoder.transform(df['item_id']) + 1

Items before filtering: 587064
Items after filtering (freq >= 5): 190466
train: 3750813 -> 2894431 rows (77.2% kept)
valid: 254376 -> 181182 rows (71.2% kept)
test: 254376 -> 172979 rows (68.0% kept)
NUM_ITEMS = 190467

In [5]:
MAX_LEN = 50

def build_user_sequences(df):
    """user_id -> list of item_idx, sorted by timestamp"""
    df_sorted = df.sort_values(['user_id', 'timestamp'])
    return df_sorted.groupby('user_id')['item_idx'].apply(list).to_dict()

def generate_sliding_windows(user_sequences, max_len=MAX_LEN, min_len=2):
    """
    Next-item prediction на кожній позиції одразу (SASRec-style).
    input:  [0,...,0, i1,i2,i3,i4]
    target: [0,...,0, i2,i3,i4,i5]
    """
    X, Y = [], []
    for seq in user_sequences.values():
        if len(seq) < min_len:
            continue
        inp = seq[:-1]
        tgt = seq[1:]
        if len(inp) >= max_len:
            inp = inp[-max_len:]
            tgt = tgt[-max_len:]
        else:
            pad = max_len - len(inp)
            inp = [0] * pad + inp
            tgt = [0] * pad + tgt
        X.append(inp)
        Y.append(tgt)
    return np.array(X), np.array(Y)

def build_val_eval_batch(user_sequences, max_len=MAX_LEN):
    """Isolates only the true held-out validation target per user,
    mirroring build_test_eval_batch — avoids contamination from
    train-only transitions inside the combined sequence."""
    X, Y = [], []
    for seq in user_sequences.values():
        if len(seq) < 2:
            continue
        inp = seq[:-1]
        target = seq[-1]
        if len(inp) >= max_len:
            inp = inp[-max_len:]
        else:
            pad = max_len - len(inp)
            inp = [0] * pad + inp
        X.append(inp)
        Y.append(target)
    return np.array(X), np.array(Y)

train_sequences = build_user_sequences(train_df)
X_train, Y_train = generate_sliding_windows(train_sequences)

valid_combined = pd.concat([train_df, valid_df])
valid_sequences = build_user_sequences(valid_combined)
X_val, y_val = build_val_eval_batch(valid_sequences, max_len=MAX_LEN)  # renamed Y_val -> y_val (single target per user, not per-position)

print(f"Train: X={X_train.shape}, Y={Y_train.shape}")
print(f"Valid: X={X_val.shape}, y={len(y_val)}")

Train: X=(127132, 50), Y=(127132, 50)
Valid: X=(127170, 50), y=127170

In [6]:
non_pad_train = (Y_train != 0).sum()
total_train = Y_train.size
print(f"Non-padding targets: {non_pad_train} out of {total_train} ({100*non_pad_train/total_train:.1f}%)")

Non-padding targets: 2204414 out of 6356600 (34.7%)

# SASRec

In [7]:
import torch
from torch.utils.data import Dataset, DataLoader

class SASRecDataset(Dataset):
    """Wraps padded (input, target) sequences for next-item prediction."""

    def __init__(self, X, Y):
        self.X = torch.tensor(X, dtype=torch.long)
        self.Y = torch.tensor(Y, dtype=torch.long)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.Y[idx]


BATCH_SIZE = 128
train_loader = DataLoader(SASRecDataset(X_train, Y_train), batch_size=BATCH_SIZE, shuffle=True)
val_loader = DataLoader(
    torch.utils.data.TensorDataset(torch.tensor(X_val, dtype=torch.long), torch.tensor(y_val, dtype=torch.long)),
    batch_size=BATCH_SIZE, shuffle=False
)  # y_val is one target per user now, not a full sequence -> use TensorDataset, same as test_loader

for x_batch, y_batch in train_loader:
    print(f"X batch shape: {x_batch.shape}, Y batch shape: {y_batch.shape}")
    break

X batch shape: torch.Size([128, 50]), Y batch shape: torch.Size([128, 50])

In [8]:
# Build a train-eval loader mirroring build_val_eval_batch: only the LAST position
# per user, so train MAP@5 is measured the same way as val MAP@5 (apples-to-apples).
# Using the full per-position X_train/Y_train for MAP@5 would be misleadingly easy,
# since many of those positions are the same transitions the model was trained on.
X_train_eval, y_train_eval = build_val_eval_batch(train_sequences, max_len=MAX_LEN)

train_eval_loader = DataLoader(
    torch.utils.data.TensorDataset(torch.tensor(X_train_eval, dtype=torch.long), torch.tensor(y_train_eval, dtype=torch.long)),
    batch_size=BATCH_SIZE, shuffle=False
)

print(f"Train-eval: X={X_train_eval.shape}, y={len(y_train_eval)}")

Train-eval: X=(127132, 50), y=127132

In [9]:
import torch.nn as nn

class SASRec(nn.Module):
    def __init__(self, num_items, max_len=MAX_LEN, d_model=64, n_heads=2, n_layers=2, dropout=0.2, emb_dropout=0.5):
        super().__init__()
        self.item_emb = nn.Embedding(num_items, d_model, padding_idx=0)
        self.pos_emb = nn.Embedding(max_len, d_model)
        self.emb_dropout = nn.Dropout(dropout)

        encoder_layer = nn.TransformerEncoderLayer(
            d_model=d_model, nhead=n_heads, dim_feedforward=d_model * 4,
            dropout=dropout, batch_first=True, activation='gelu',
        )
        self.encoder = nn.TransformerEncoder(encoder_layer, num_layers=n_layers)
        self.layer_norm = nn.LayerNorm(d_model)
        self.max_len = max_len

    def forward(self, item_seq):
        batch_size, seq_len = item_seq.shape
        positions = torch.arange(seq_len, device=item_seq.device).unsqueeze(0).expand(batch_size, -1)

        x = self.item_emb(item_seq) + self.pos_emb(positions)
        x = self.emb_dropout(x)

        causal_mask = nn.Transformer.generate_square_subsequent_mask(seq_len).to(item_seq.device)
        padding_mask = (item_seq == 0)

        x = self.encoder(x, mask=causal_mask, src_key_padding_mask=padding_mask)

        # padding-only query positions can produce NaN internally (fully-masked attention row);
        # those positions are excluded from the loss anyway, so zeroing NaNs here is safe
        # and stops them from contaminating real positions in later computations
        x = torch.nan_to_num(x, nan=0.0)

        x = self.layer_norm(x)
        return x

    def predict_logits(self, hidden_states):
        return hidden_states @ self.item_emb.weight.T

In [10]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = SASRec(num_items=NUM_ITEMS, max_len=MAX_LEN, d_model=64, n_heads=2, n_layers=2, dropout=0.2).to(device)

criterion = nn.CrossEntropyLoss(label_smoothing=0.1)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-4)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', patience=1, factor=0.5)

print(f"Device: {device}")
print(f"Model parameters: {sum(p.numel() for p in model.parameters()):,}")

Device: cuda
Model parameters: 12,293,184

In [11]:
item_domain = np.array(['pad'] + [
    'books' if c.startswith('books::') else 'movies'
    for c in encoder.classes_
])

domain_id = torch.tensor(
    [0 if d == 'pad' else (1 if d == 'books' else 2) for d in item_domain],
    device=device
)
books_item_idx = torch.tensor(np.where(item_domain == 'books')[0], device=device)
movies_item_idx = torch.tensor(np.where(item_domain == 'movies')[0], device=device)

print(f"Books items: {len(books_item_idx)}, Movies items: {len(movies_item_idx)}")

Books items: 106241, Movies items: 84225

In [12]:
# # Popularity-weighted negative sampling: negatives should be sampled proportional
# # to how often each item appears in train, not uniformly. Uniform negatives are
# # almost always obscure long-tail items — trivially easy to distinguish from the
# # true target — so the model never learns to out-rank genuinely popular competitors,
# # which is exactly why it currently fails to beat the popularity baseline.
# item_pop_counts = train_df['item_idx'].value_counts()
# full_pop_counts = np.zeros(NUM_ITEMS)
# full_pop_counts[item_pop_counts.index.values] = item_pop_counts.values
# full_pop_counts_t = torch.tensor(full_pop_counts, device=device, dtype=torch.float)

# # smoothing exponent (0.75, as in word2vec negative sampling) prevents the
# # most popular items from dominating the negative pool entirely
# POP_SMOOTHING = 0.75
# smoothed_pop = full_pop_counts_t.clamp(min=1.0) ** POP_SMOOTHING

# books_neg_weights = smoothed_pop[books_item_idx]
# movies_neg_weights = smoothed_pop[movies_item_idx]

# print(f"Books weight range: {books_neg_weights.min().item():.1f} - {books_neg_weights.max().item():.1f}")
# print(f"Movies weight range: {movies_neg_weights.min().item():.1f} - {movies_neg_weights.max().item():.1f}")

In [13]:
def sampled_logits_and_labels(model, hidden_valid, targets_valid, num_items, num_negatives=100):
    N = hidden_valid.size(0)
    device = hidden_valid.device

    # Sample negatives from the SAME domain as the target, so the model can't
    # shortcut on "is this a book or a movie" instead of learning real relevance
    target_domain_id = domain_id[targets_valid]
    is_books = target_domain_id == 1

    books_sample_idx = torch.randint(0, len(books_item_idx), (N, num_negatives), device=device)
    movies_sample_idx = torch.randint(0, len(movies_item_idx), (N, num_negatives), device=device)
    neg_items = torch.where(
        is_books.unsqueeze(1),
        books_item_idx[books_sample_idx],
        movies_item_idx[movies_sample_idx],
    )

    collision = neg_items == targets_valid.unsqueeze(1)
    if collision.any():
        n_coll = int(collision.sum().item())
        fallback_books = books_item_idx[torch.randint(0, len(books_item_idx), (n_coll,), device=device)]
        fallback_movies = movies_item_idx[torch.randint(0, len(movies_item_idx), (n_coll,), device=device)]
        is_books_flat = is_books.unsqueeze(1).expand(-1, num_negatives)[collision]
        neg_items[collision] = torch.where(is_books_flat, fallback_books, fallback_movies)

    candidates = torch.cat([targets_valid.unsqueeze(1), neg_items], dim=1)   # (N, 1+K)
    cand_emb = model.item_emb(candidates)                                    # (N, 1+K, d_model)

    logits = torch.bmm(cand_emb, hidden_valid.unsqueeze(-1)).squeeze(-1)     # (N, 1+K)
    labels = torch.zeros(N, dtype=torch.long, device=device)                 # correct item is always at index 0

    return logits, labels

In [14]:
@torch.no_grad()
def evaluate_map_at_k(model, hidden_valid, targets_valid, num_items, num_negatives=100, k=5):
    """
    Builds candidate-pool rankings and scores them with the repo's map_at_k
    (relies on average_precision_at_k under the hood).
    Each "user" here is really one (position, target) example — with a single
    relevant item — matching the interface map_at_k expects.
    """
    model.eval()
    N = hidden_valid.size(0)
    device = hidden_valid.device

    neg_items = torch.randint(1, num_items, (N, num_negatives), device=device)
    collision = neg_items == targets_valid.unsqueeze(1)
    if collision.any():
        neg_items[collision] = torch.randint(1, num_items, (int(collision.sum().item()),), device=device)

    candidates = torch.cat([targets_valid.unsqueeze(1), neg_items], dim=1)   # (N, 1+K)
    cand_emb = model.item_emb(candidates)
    logits = torch.bmm(cand_emb, hidden_valid.unsqueeze(-1)).squeeze(-1)      # (N, 1+K)

    top_k_idx = logits.topk(k, dim=1).indices                                # (N, k), indices into candidate axis
    top_k_items = torch.gather(candidates, 1, top_k_idx)                     # (N, k), actual item ids

    recommended_items_by_user = {i: top_k_items[i].tolist() for i in range(N)}
    relevant_items_by_user = {i: [targets_valid[i].item()] for i in range(N)}

    return map_at_k(recommended_items_by_user, relevant_items_by_user, k=k)

In [15]:
@torch.no_grad()
def sampled_ranking_map_at_k(model, hidden_all, targets_all, num_items, num_negatives=999, k=5, seed=42, chunk_size=2048):
    model.eval()
    device = hidden_all.device
    generator = torch.Generator(device=device).manual_seed(seed)

    recommended_items_by_user = {}
    relevant_items_by_user = {}
    global_idx = 0

    for start in range(0, hidden_all.size(0), chunk_size):
        end = start + chunk_size
        hidden_chunk = hidden_all[start:end]
        targets_chunk = targets_all[start:end]
        n = hidden_chunk.size(0)

        target_domain_id_chunk = domain_id[targets_chunk]
        is_books_chunk = target_domain_id_chunk == 1
        books_sample_idx = torch.randint(0, len(books_item_idx), (n, num_negatives), device=device, generator=generator)
        movies_sample_idx = torch.randint(0, len(movies_item_idx), (n, num_negatives), device=device, generator=generator)
        neg_items = torch.where(
            is_books_chunk.unsqueeze(1),
            books_item_idx[books_sample_idx],
            movies_item_idx[movies_sample_idx],
        )

        collision = neg_items == targets_chunk.unsqueeze(1)
        if collision.any():
            n_coll = int(collision.sum().item())
            fallback_books = books_item_idx[torch.randint(0, len(books_item_idx), (n_coll,), device=device, generator=generator)]
            fallback_movies = movies_item_idx[torch.randint(0, len(movies_item_idx), (n_coll,), device=device, generator=generator)]
            is_books_flat = is_books_chunk.unsqueeze(1).expand(-1, num_negatives)[collision]
            neg_items[collision] = torch.where(is_books_flat, fallback_books, fallback_movies)

        candidates = torch.cat([targets_chunk.unsqueeze(1), neg_items], dim=1)   # (n, 1+K)
        cand_emb = model.item_emb(candidates)
        logits = torch.bmm(cand_emb, hidden_chunk.unsqueeze(-1)).squeeze(-1)      # (n, 1+K)

        top_k_idx = logits.topk(k, dim=1).indices
        top_k_items = torch.gather(candidates, 1, top_k_idx)

        for i in range(n):
            recommended_items_by_user[global_idx] = top_k_items[i].tolist()
            relevant_items_by_user[global_idx] = [targets_chunk[i].item()]
            global_idx += 1

    return map_at_k(recommended_items_by_user, relevant_items_by_user, k=k)

## Training

In [16]:
import wandb

wandb.init(
    project="recsys-sequential",
    name="sasrec-v4-dmodel64",
    config={
        "model": "SASRec",
        "max_len": MAX_LEN,
        "d_model": 64,
        "n_heads": 2,
        "n_layers": 2,
        "dropout": 0.2,
        "batch_size": BATCH_SIZE,
        "lr": 1e-3,
        "weight_decay": 1e-4,
    }
)

/usr/local/lib/python3.12/dist-packages/notebook/notebookapp.py:191: SyntaxWarning: invalid escape sequence '\/'
  | |_| | '_ \/ _` / _` |  _/ -_)
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results

wandb: Enter your choice: 2

wandb: You chose 'Use an existing W&B account'
wandb: Logging into https://api.wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: Create a new API key at: https://wandb.ai/authorize?ref=models
wandb: Store your API key securely and do not share it.

wandb: Paste your API key and hit enter: ··········

wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: rsai2026_2 (rsai2026_2-kyiv-school-of-economics) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

In [17]:
EPOCHS = 30
PATIENCE = 5
MIN_DELTA = 0.0
MIN_EPOCHS_BEFORE_STOPPING = 10
WARMUP_EPOCHS = 5
best_val_map = -float('inf')
patience_counter = 0
best_state = None

for epoch in range(EPOCHS):
    model.train()
    train_loss = 0.0
    total_grad_norm = 0.0

    for x_batch, y_batch in train_loader:
        x_batch, y_batch = x_batch.to(device), y_batch.to(device)
        optimizer.zero_grad()
        hidden = model(x_batch)

        # Flatten and keep only non-padding positions BEFORE the expensive matmul
        hidden_flat = hidden.view(-1, hidden.size(-1))
        targets_flat = y_batch.view(-1)
        mask = targets_flat != 0
        hidden_valid = hidden_flat[mask]
        targets_valid = targets_flat[mask]

        logits, labels = sampled_logits_and_labels(model, hidden_valid, targets_valid, NUM_ITEMS, num_negatives=100)
        loss = criterion(logits, labels)
        loss.backward()

        grad_norm = torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=2.0)
        total_grad_norm += grad_norm.item()

        optimizer.step()
        train_loss += loss.item()

    train_loss /= len(train_loader)
    avg_grad_norm = total_grad_norm / len(train_loader)

    model.eval()
    val_loss = 0.0
    all_hidden = []
    all_targets = []

    with torch.no_grad():
        for x_batch, y_batch in val_loader:
            x_batch, y_batch = x_batch.to(device), y_batch.to(device)
            hidden = model(x_batch)

            # y_batch is now a single held-out target per user -> take only the LAST position's hidden state,
            # matching how build_val_eval_batch left-pads (last position = last real history item -> predicts y_batch)
            hidden_valid = hidden[:, -1, :]
            targets_valid = y_batch

            all_hidden.append(hidden_valid.cpu())
            all_targets.append(targets_valid.cpu())

            logits, labels = sampled_logits_and_labels(model, hidden_valid, targets_valid, NUM_ITEMS, num_negatives=100)
            loss = criterion(logits, labels)
            val_loss += loss.item()

    val_loss /= len(val_loader)

    all_hidden = torch.cat(all_hidden).to(device)
    all_targets = torch.cat(all_targets).to(device)
    val_map5 = sampled_ranking_map_at_k(model, all_hidden, all_targets, NUM_ITEMS, num_negatives=999, k=5, seed=42)

    # Train MAP@5 for overfit tracking — same last-position-only protocol as val,
    # so the train/val gap is a real generalization gap, not a measurement artifact
    all_hidden_train_eval, all_targets_train_eval = [], []
    with torch.no_grad():
        for x_batch, y_batch in train_eval_loader:
            x_batch, y_batch = x_batch.to(device), y_batch.to(device)
            hidden = model(x_batch)
            all_hidden_train_eval.append(hidden[:, -1, :].cpu())
            all_targets_train_eval.append(y_batch.cpu())

    all_hidden_train_eval = torch.cat(all_hidden_train_eval).to(device)
    all_targets_train_eval = torch.cat(all_targets_train_eval).to(device)
    train_map5 = sampled_ranking_map_at_k(model, all_hidden_train_eval, all_targets_train_eval, NUM_ITEMS, num_negatives=999, k=5, seed=42)

    scheduler.step(val_loss)
    current_lr = optimizer.param_groups[0]['lr']

    wandb.log({
        "epoch": epoch + 1,
        "train_loss": train_loss,
        "val_loss": val_loss,
        "grad_norm": avg_grad_norm,
        "learning_rate": current_lr,
        "val_map@5": val_map5,
        "train_map@5": train_map5,
        "overfit_gap_map@5": train_map5 - val_map5,
    })

    print(f"Epoch [{epoch+1}/{EPOCHS}] Train Loss: {train_loss:.4f} | Val Loss: {val_loss:.4f} | Train MAP@5: {train_map5:.4f} | Val MAP@5: {val_map5:.4f} | Gap: {train_map5 - val_map5:.4f} | Grad Norm: {avg_grad_norm:.4f}")

    if epoch + 1 > WARMUP_EPOCHS and val_map5 > best_val_map + MIN_DELTA:
        best_val_map = val_map5
        best_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}
        patience_counter = 0
    else:
        patience_counter += 1
        if epoch + 1 >= MIN_EPOCHS_BEFORE_STOPPING and patience_counter >= PATIENCE:
            print(f"Early stopping at epoch {epoch+1}")
            break

model.load_state_dict(best_state)
wandb.finish()

/usr/local/lib/python3.12/dist-packages/torch/nn/modules/transformer.py:431: UserWarning: Support for mismatched src_key_padding_mask and mask is deprecated. Use same type for both instead.
  src_key_padding_mask = F._canonical_mask(

Epoch [1/30] Train Loss: 7.3086 | Val Loss: 6.0886 | Train MAP@5: 0.0018 | Val MAP@5: 0.0021 | Gap: -0.0003 | Grad Norm: 1.5169
Epoch [2/30] Train Loss: 4.5859 | Val Loss: 4.8845 | Train MAP@5: 0.0033 | Val MAP@5: 0.0037 | Gap: -0.0004 | Grad Norm: 0.1436
Epoch [3/30] Train Loss: 4.2864 | Val Loss: 4.4799 | Train MAP@5: 0.0282 | Val MAP@5: 0.0270 | Gap: 0.0012 | Grad Norm: 0.1094
Epoch [4/30] Train Loss: 4.1183 | Val Loss: 4.3651 | Train MAP@5: 0.0496 | Val MAP@5: 0.0454 | Gap: 0.0042 | Grad Norm: 0.1620
Epoch [5/30] Train Loss: 3.9131 | Val Loss: 4.3413 | Train MAP@5: 0.0564 | Val MAP@5: 0.0511 | Gap: 0.0053 | Grad Norm: 0.3323
Epoch [6/30] Train Loss: 3.7061 | Val Loss: 4.3631 | Train MAP@5: 0.0572 | Val MAP@5: 0.0510 | Gap: 0.0061 | Grad Norm: 0.5547
Epoch [7/30] Train Loss: 3.5291 | Val Loss: 4.3766 | Train MAP@5: 0.0576 | Val MAP@5: 0.0517 | Gap: 0.0059 | Grad Norm: 0.7158
Epoch [8/30] Train Loss: 3.2992 | Val Loss: 4.3832 | Train MAP@5: 0.0593 | Val MAP@5: 0.0531 | Gap: 0.0062 | Grad Norm: 0.7966
Epoch [9/30] Train Loss: 3.1949 | Val Loss: 4.3910 | Train MAP@5: 0.0596 | Val MAP@5: 0.0536 | Gap: 0.0060 | Grad Norm: 0.9217
Epoch [10/30] Train Loss: 3.0458 | Val Loss: 4.3918 | Train MAP@5: 0.0599 | Val MAP@5: 0.0535 | Gap: 0.0064 | Grad Norm: 0.9787
Epoch [11/30] Train Loss: 2.9825 | Val Loss: 4.3944 | Train MAP@5: 0.0602 | Val MAP@5: 0.0530 | Gap: 0.0072 | Grad Norm: 1.1057
Epoch [12/30] Train Loss: 2.8803 | Val Loss: 4.3949 | Train MAP@5: 0.0606 | Val MAP@5: 0.0528 | Gap: 0.0079 | Grad Norm: 1.1447
Epoch [13/30] Train Loss: 2.8406 | Val Loss: 4.3959 | Train MAP@5: 0.0603 | Val MAP@5: 0.0521 | Gap: 0.0083 | Grad Norm: 1.2656
Epoch [14/30] Train Loss: 2.7767 | Val Loss: 4.3961 | Train MAP@5: 0.0606 | Val MAP@5: 0.0521 | Gap: 0.0085 | Grad Norm: 1.2914
Early stopping at epoch 14

## Validate on test set

In [18]:
test_combined = pd.concat([train_df, valid_df, test_df])
test_sequences = build_user_sequences(test_combined)

def build_test_eval_batch(user_sequences, max_len=MAX_LEN):
    """
    For each user: history = everything except the last interaction,
    target = the last interaction (the held-out test item to predict).
    Left-padding guarantees the last position in each row is always
    the last real history item (never padding), as long as history has >=1 item.
    """
    X, Y = [], []
    for seq in user_sequences.values():
        if len(seq) < 2:
            continue
        inp = seq[:-1]
        target = seq[-1]
        if len(inp) >= max_len:
            inp = inp[-max_len:]
        else:
            pad = max_len - len(inp)
            inp = [0] * pad + inp
        X.append(inp)
        Y.append(target)
    return np.array(X), np.array(Y)

X_test, y_test = build_test_eval_batch(test_sequences)
print(f"Test: X={X_test.shape}, y={len(y_test)}")

Test: X=(127184, 50), y=127184

In [19]:
model.eval()

test_loader = DataLoader(
    torch.utils.data.TensorDataset(torch.tensor(X_test, dtype=torch.long), torch.tensor(y_test, dtype=torch.long)),
    batch_size=BATCH_SIZE, shuffle=False
)

all_hidden_test, all_targets_test = [], []
with torch.no_grad():
    for x_batch, y_batch in test_loader:
        x_batch = x_batch.to(device)
        hidden = model(x_batch)
        all_hidden_test.append(hidden[:, -1, :].cpu())   # last position = prediction for the held-out item
        all_targets_test.append(y_batch)

all_hidden_test = torch.cat(all_hidden_test).to(device)
all_targets_test = torch.cat(all_targets_test).to(device)

print(f"all_hidden_test: {all_hidden_test.shape}, all_targets_test: {all_targets_test.shape}")

/usr/local/lib/python3.12/dist-packages/torch/nn/modules/transformer.py:431: UserWarning: Support for mismatched src_key_padding_mask and mask is deprecated. Use same type for both instead.
  src_key_padding_mask = F._canonical_mask(

all_hidden_test: torch.Size([127184, 64]), all_targets_test: torch.Size([127184])

In [20]:
def average_metric_over_users(metric_fn, recommended_by_user, relevant_by_user, k):
    """Applies a per-user metric function (ndcg_at_k, recall_at_k, precision_at_k)
    across a dict of users and averages the result — mirrors what map_at_k does
    internally via average_precision_at_k, since those other functions don't have
    their own dict-aware wrapper in the repo.
    """
    scores = [
        metric_fn(recommended_by_user.get(user_id, []), relevant_items, k=k)
        for user_id, relevant_items in relevant_by_user.items()
    ]
    return sum(scores) / len(scores) if scores else 0.0

In [21]:
import gc

if 'optimizer' in globals():
    del optimizer
if 'scheduler' in globals():
    del scheduler

gc.collect()
torch.cuda.empty_cache()

print(f"Free GPU memory: {torch.cuda.mem_get_info()[0] / 1e9:.2f} GB")

@torch.no_grad()
def full_ranking_eval(model, hidden_all, targets_all, num_items, k_list=(5, 10), chunk_size=2048):
    """Returns top-k recommended items dict + relevant items dict, ready for map_at_k/ndcg_at_k/recall_at_k."""
    max_k = max(k_list)
    all_item_emb = model.item_emb.weight
    recommended_items_by_user = {}
    relevant_items_by_user = {}
    global_idx = 0

    for start in range(0, hidden_all.size(0), chunk_size):
        end = start + chunk_size
        hidden_chunk = hidden_all[start:end]
        targets_chunk = targets_all[start:end]

        logits_chunk = hidden_chunk @ all_item_emb.T

        # Restrict candidates to the same domain as each row's target item
        # (also implicitly excludes padding, since domain_id[0] == 0 and no real target has domain_id 0)
        target_domain_id_chunk = domain_id[targets_chunk]                            # (n,)
        wrong_domain_mask = domain_id.unsqueeze(0) != target_domain_id_chunk.unsqueeze(1)  # (n, num_items)
        logits_chunk = logits_chunk.masked_fill(wrong_domain_mask, float('-inf'))

        top_k_items = logits_chunk.topk(max_k, dim=1).indices

        for i in range(hidden_chunk.size(0)):
            recommended_items_by_user[global_idx] = top_k_items[i].tolist()
            relevant_items_by_user[global_idx] = [targets_chunk[i].item()]
            global_idx += 1

    return recommended_items_by_user, relevant_items_by_user

recommended_model, relevant_items = full_ranking_eval(model, all_hidden_test, all_targets_test, NUM_ITEMS,  chunk_size=128)

model_metrics = {
    "MAP@5": map_at_k(recommended_model, relevant_items, k=5),
    "NDCG@10": average_metric_over_users(ndcg_at_k, recommended_model, relevant_items, k=10),
    "Recall@10": average_metric_over_users(recall_at_k, recommended_model, relevant_items, k=10),
}
print("Model:", model_metrics)

Free GPU memory: 15.15 GB
Model: {'MAP@5': 0.001730039417956137, 'NDCG@10': np.float64(0.003002905622345981), 'Recall@10': 0.006172160020128318}

In [22]:
books_item_idx_np = books_item_idx.cpu().numpy()
movies_item_idx_np = movies_item_idx.cpu().numpy()

top_popular_books = train_df.loc[train_df['item_idx'].isin(books_item_idx_np), 'item_idx'].value_counts().index[:10].tolist()
top_popular_movies = train_df.loc[train_df['item_idx'].isin(movies_item_idx_np), 'item_idx'].value_counts().index[:10].tolist()

rng = np.random.default_rng(42)
recommended_popular = {}
recommended_random = {}
for i, target_item in enumerate(y_test):
    is_books_target = item_domain[target_item] == 'books'
    recommended_popular[i] = top_popular_books if is_books_target else top_popular_movies
    pool = books_item_idx_np if is_books_target else movies_item_idx_np
    recommended_random[i] = rng.choice(pool, size=10, replace=False).tolist()

# assumes model_metrics, popular_metrics, random_metrics dicts already computed, e.g.:
# model_metrics = {"MAP@5": ..., "NDCG@10": ..., "Recall@10": ...}
popular_metrics = {
    "MAP@5": map_at_k(recommended_popular, relevant_items, k=5),
    "NDCG@10": average_metric_over_users(ndcg_at_k, recommended_popular, relevant_items, k=10),
    "Recall@10": average_metric_over_users(recall_at_k, recommended_popular, relevant_items, k=10),
}
random_metrics = {
    "MAP@5": map_at_k(recommended_random, relevant_items, k=5),
    "NDCG@10": average_metric_over_users(ndcg_at_k, recommended_random, relevant_items, k=10),
    "Recall@10": average_metric_over_users(recall_at_k, recommended_random, relevant_items, k=10),
}

rows = []
for metric in model_metrics:
    model_val = model_metrics[metric]
    popular_val = popular_metrics[metric]
    random_val = random_metrics[metric]

    lift_popular = model_val / popular_val if popular_val > 0 else float('inf')
    lift_random = model_val / random_val if random_val > 0 else float('inf')

    rows.append({
        "Metric": metric,
        "Model": model_val,
        "Top-Popular": popular_val,
        "Random": random_val,
        "Lift vs Popular": lift_popular,
        "Lift vs Random": lift_random,
    })

df = pd.DataFrame(rows)

# nice formatting: small decimals for raw metrics, "x" suffix for lift, inf handled gracefully
formatted = df.copy()
for col in ["Model", "Top-Popular", "Random"]:
    formatted[col] = formatted[col].map(lambda v: f"{v:.6f}")
for col in ["Lift vs Popular", "Lift vs Random"]:
    formatted[col] = formatted[col].map(lambda v: "∞" if v == float('inf') else f"×{v:.2f}")

print(formatted.to_string(index=False))

   Metric    Model Top-Popular   Random Lift vs Popular Lift vs Random
    MAP@5 0.001730    0.001834 0.000037           ×0.94         ×46.49
  NDCG@10 0.003003    0.002998 0.000060           ×1.00         ×50.38
Recall@10 0.006172    0.006015 0.000118           ×1.03         ×52.33

In [23]:
def split_by_domain(relevant_items_by_user, item_domain):
    """Splits user indices into 'books' and 'movies' groups based on
    the domain of their relevant (held-out target) item."""
    books_users, movies_users = [], []
    for user_id, relevant in relevant_items_by_user.items():
        target_item = relevant[0]
        if item_domain[target_item] == 'books':
            books_users.append(user_id)
        else:
            movies_users.append(user_id)
    return books_users, movies_users


def subset_dict(d, user_ids):
    return {u: d[u] for u in user_ids}


def compute_metrics_for_subset(recommended, relevant, user_ids):
    rec_subset = subset_dict(recommended, user_ids)
    rel_subset = subset_dict(relevant, user_ids)
    return {
        "MAP@5": map_at_k(rec_subset, rel_subset, k=5),
        "NDCG@10": average_metric_over_users(ndcg_at_k, rec_subset, rel_subset, k=10),
        "Recall@10": average_metric_over_users(recall_at_k, rec_subset, rel_subset, k=10),
    }


books_users, movies_users = split_by_domain(relevant_items, item_domain)
print(f"Books users: {len(books_users)}, Movies users: {len(movies_users)}")

results_by_domain = {}
for domain_name, user_ids in (("Books", books_users), ("Movies", movies_users)):
    model_d = compute_metrics_for_subset(recommended_model, relevant_items, user_ids)
    popular_d = compute_metrics_for_subset(recommended_popular, relevant_items, user_ids)
    random_d = compute_metrics_for_subset(recommended_random, relevant_items, user_ids)

    rows = []
    for metric in model_d:
        model_val = model_d[metric]
        popular_val = popular_d[metric]
        random_val = random_d[metric]
        lift_popular = model_val / popular_val if popular_val > 0 else float('inf')
        lift_random = model_val / random_val if random_val > 0 else float('inf')
        rows.append({
            "Metric": metric,
            "Model": model_val,
            "Top-Popular": popular_val,
            "Random": random_val,
            "Lift vs Popular": lift_popular,
            "Lift vs Random": lift_random,
        })

    df_domain = pd.DataFrame(rows)
    formatted = df_domain.copy()
    for col in ["Model", "Top-Popular", "Random"]:
        formatted[col] = formatted[col].map(lambda v: f"{v:.6f}")
    for col in ["Lift vs Popular", "Lift vs Random"]:
        formatted[col] = formatted[col].map(lambda v: "∞" if v == float('inf') else f"×{v:.2f}")

    print(f"\n=== {domain_name} ===")
    print(formatted.to_string(index=False))
    results_by_domain[domain_name] = df_domain

Books users: 63034, Movies users: 64150

=== Books ===
   Metric    Model Top-Popular   Random Lift vs Popular Lift vs Random
    MAP@5 0.001482    0.001262 0.000045           ×1.17         ×32.59
  NDCG@10 0.002668    0.002172 0.000064           ×1.23         ×41.67
Recall@10 0.005648    0.004347 0.000111           ×1.30         ×50.86

=== Movies ===
   Metric    Model Top-Popular   Random Lift vs Popular Lift vs Random
    MAP@5 0.001974    0.002397 0.000029           ×0.82         ×67.83
  NDCG@10 0.003332    0.003810 0.000055           ×0.87         ×60.28
Recall@10 0.006687    0.007654 0.000125           ×0.87         ×53.63

## Saving metrics results

In [24]:
def extract_metric(df_domain, column, metric):
    return float(df_domain.set_index('Metric')[column][metric])

def sasrec_result_row(model_name, column):
    row = {
        'model': model_name,
        'd_model': 64, 'n_heads': 2, 'n_layers': 2,
        'k': 10, 'map_k': 5,
        'n_users': train_df['user_id'].nunique(),
        'n_items': NUM_ITEMS - 1,
    }
    for metric_label, key in [('MAP@5', 'map@5'), ('NDCG@10', 'ndcg@10'), ('Recall@10', 'recall@10')]:
        books_val = extract_metric(results_by_domain['Books'], column, metric_label)
        movies_val = extract_metric(results_by_domain['Movies'], column, metric_label)
        row[f'books_test_{key}'] = round(books_val, 4)
        row[f'movies_test_{key}'] = round(movies_val, 4)
        row[f'test_macro_{key}'] = round((books_val + movies_val) / 2, 4)
    return row

sasrec_metrics_results = pd.DataFrame([
    sasrec_result_row('sasrec_books_movies_joint', 'Model'),
    sasrec_result_row('popularity_baseline', 'Top-Popular'),
    sasrec_result_row('random_baseline', 'Random'),
])

RESULTS_DIR = f'{DATA_DIR}/results'
os.makedirs(RESULTS_DIR, exist_ok=True)
sasrec_metrics_results.to_csv(f'{RESULTS_DIR}/sasrec_metrics.csv', index=False)
sasrec_metrics_results

,model,d_model,n_heads,n_layers,k,map_k,n_users,n_items,books_test_map@5,movies_test_map@5,test_macro_map@5,books_test_ndcg@10,movies_test_ndcg@10,test_macro_ndcg@10,books_test_recall@10,movies_test_recall@10,test_macro_recall@10
0,sasrec_books_movies_joint,64,2,2,10,5,127183,190466,0.0015,0.0020,0.0017,0.0027,0.0033,0.0030,0.0056,0.0067,0.0062
1,popularity_baseline,64,2,2,10,5,127183,190466,0.0013,0.0024,0.0018,0.0022,0.0038,0.0030,0.0043,0.0077,0.0060
2,random_baseline,64,2,2,10,5,127183,190466,0.0000,0.0000,0.0000,0.0001,0.0001,0.0001,0.0001,0.0001,0.0001

## Export artifacts for the app MVP

In [25]:
import json

ARTIFACTS_DIR = f'{DATA_DIR}/artifacts/sasrec'
os.makedirs(ARTIFACTS_DIR, exist_ok=True)

torch.save(model.state_dict(), f'{ARTIFACTS_DIR}/model_state_dict.pt')

item2idx = {cls: i + 1 for i, cls in enumerate(encoder.classes_)}
with open(f'{ARTIFACTS_DIR}/item2idx.json', 'w') as f:
    json.dump(item2idx, f)

with open(f'{ARTIFACTS_DIR}/domain_item_indices.json', 'w') as f:
    json.dump({
        'books': books_item_idx.cpu().tolist(),
        'movies': movies_item_idx.cpu().tolist(),
    }, f)

with open(f'{ARTIFACTS_DIR}/config.json', 'w') as f:
    json.dump({
        'num_items': NUM_ITEMS,
        'max_len': MAX_LEN,
        'd_model': 64,
        'n_heads': 2,
        'n_layers': 2,
        'dropout': 0.2,
    }, f)

print(f'Saved SASRec artifacts to {ARTIFACTS_DIR}')

Saved SASRec artifacts to /content/drive/MyDrive/recsys-data/artifacts/sasrec

# Bert4Rec

In [26]:
# --- BERT4Rec: masked (Cloze) training data + leave-one-out eval data ---

MASK_TOKEN = NUM_ITEMS  # new id beyond real items (0=padding, 1..NUM_ITEMS-1=items, NUM_ITEMS=[MASK])
MASK_PROB = 0.2         # fraction of REAL (non-padding) positions masked per sequence

def build_bert4rec_training_batch(user_sequences, max_len=MAX_LEN, mask_prob=MASK_PROB, rng=None):
    """
    Cloze-style masking (as in original BERT4Rec paper):
      - pick ~mask_prob of real (non-padding) positions per sequence
      - of those: 80% -> replace with [MASK], 10% -> replace with random item, 10% -> leave unchanged
      - target at masked positions = original item id; target=0 elsewhere (ignored in loss, same
        convention as padding_idx=0, since no real item has index 0)
    Regenerate this EVERY epoch (dynamic masking) — re-masking the same sequences differently
    each epoch is a meaningful data augmentation and is standard practice for BERT4Rec.
    """
    rng = rng or np.random.default_rng()
    X, Y = [], []
    for seq in user_sequences.values():
        if len(seq) < 2:
            continue
        seq = seq[-max_len:] if len(seq) > max_len else seq
        pad = max_len - len(seq)
        inp = [0] * pad + list(seq)
        tgt = [0] * max_len

        real_positions = list(range(pad, max_len))
        n_mask = max(1, int(round(len(real_positions) * mask_prob)))
        mask_positions = rng.choice(real_positions, size=min(n_mask, len(real_positions)), replace=False)

        for i in mask_positions:
            tgt[i] = inp[i]
            r = rng.random()
            if r < 0.8:
                inp[i] = MASK_TOKEN
            elif r < 0.9:
                inp[i] = int(rng.integers(1, NUM_ITEMS))  # random real item, never MASK/padding
            # else: leave unchanged (model still must predict tgt[i] correctly)

        X.append(inp)
        Y.append(tgt)
    return np.array(X), np.array(Y)


def build_bert4rec_eval_batch(user_sequences, max_len=MAX_LEN, mask_token=MASK_TOKEN):
    """
    Leave-one-out eval, BERT4Rec style: history (everything except the held-out item)
    gets a [MASK] appended at the END, left-padded. The hidden state at the LAST position
    (the [MASK] position) is used for prediction — this keeps hidden[:, -1, :] downstream
    code identical to what SASRec eval already uses.
    """
    X, Y = [], []
    for seq in user_sequences.values():
        if len(seq) < 2:
            continue
        inp_hist = seq[:-1]
        target = seq[-1]
        if len(inp_hist) >= max_len - 1:       # leave room for the appended [MASK]
            inp_hist = inp_hist[-(max_len - 1):]
        seq_with_mask = list(inp_hist) + [mask_token]
        pad = max_len - len(seq_with_mask)
        X.append([0] * pad + seq_with_mask)
        Y.append(target)
    return np.array(X), np.array(Y)


# Build eval sets (static — no masking randomness needed here, same as SASRec's build_val_eval_batch)
X_val_bert, y_val_bert = build_bert4rec_eval_batch(valid_sequences, max_len=MAX_LEN)
X_train_eval_bert, y_train_eval_bert = build_bert4rec_eval_batch(train_sequences, max_len=MAX_LEN)

print(f"Val (BERT4Rec eval): X={X_val_bert.shape}, y={len(y_val_bert)}")
print(f"Train-eval (BERT4Rec eval): X={X_train_eval_bert.shape}, y={len(y_train_eval_bert)}")

val_loader_bert = DataLoader(
    torch.utils.data.TensorDataset(torch.tensor(X_val_bert, dtype=torch.long), torch.tensor(y_val_bert, dtype=torch.long)),
    batch_size=BATCH_SIZE, shuffle=False
)
train_eval_loader_bert = DataLoader(
    torch.utils.data.TensorDataset(torch.tensor(X_train_eval_bert, dtype=torch.long), torch.tensor(y_train_eval_bert, dtype=torch.long)),
    batch_size=BATCH_SIZE, shuffle=False
)

Val (BERT4Rec eval): X=(127170, 50), y=127170
Train-eval (BERT4Rec eval): X=(127132, 50), y=127132

In [27]:
class BERT4Rec(nn.Module):
    def __init__(self, num_items, mask_token, max_len=MAX_LEN, d_model=64, n_heads=2, n_layers=2,
                 dropout=0.2, emb_dropout=0.5):
        super().__init__()
        vocab_size = num_items + 1  # +1 row reserved for [MASK] token id = num_items
        self.item_emb = nn.Embedding(vocab_size, d_model, padding_idx=0)
        self.pos_emb = nn.Embedding(max_len, d_model)
        self.emb_dropout = nn.Dropout(emb_dropout)

        encoder_layer = nn.TransformerEncoderLayer(
            d_model=d_model, nhead=n_heads, dim_feedforward=d_model * 4,
            dropout=dropout, batch_first=True, activation='gelu',
        )
        self.encoder = nn.TransformerEncoder(encoder_layer, num_layers=n_layers)
        self.layer_norm = nn.LayerNorm(d_model)
        self.max_len = max_len
        self.mask_token = mask_token
        self.num_items = num_items

    def forward(self, item_seq):
        batch_size, seq_len = item_seq.shape
        positions = torch.arange(seq_len, device=item_seq.device).unsqueeze(0).expand(batch_size, -1)

        x = self.item_emb(item_seq) + self.pos_emb(positions)
        x = self.emb_dropout(x)

        # NO causal mask here — this is the core difference from SASRec: every position
        # can attend to both earlier AND later positions (bidirectional context).
        padding_mask = (item_seq == 0)
        x = self.encoder(x, src_key_padding_mask=padding_mask)

        x = torch.nan_to_num(x, nan=0.0)
        x = self.layer_norm(x)
        return x

    def real_item_embeddings(self):
        """Embedding matrix restricted to real items (0=padding included, [MASK] row excluded) —
        use this whenever scoring against the real catalog, so [MASK] can never be recommended."""
        return self.item_emb.weight[:self.num_items]

In [28]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = BERT4Rec(num_items=NUM_ITEMS, mask_token=MASK_TOKEN, max_len=MAX_LEN,
                  d_model=64, n_heads=2, n_layers=2, dropout=0.2, emb_dropout=0.5).to(device)

criterion = nn.CrossEntropyLoss(label_smoothing=0.1)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-4)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', patience=1, factor=0.5)

print(f"Device: {device}")
print(f"Model parameters: {sum(p.numel() for p in model.parameters()):,}")

Device: cuda
Model parameters: 12,293,248

## Training

In [29]:
import wandb

wandb.init(
    project="recsys-sequential",
    name="bert4rec-v1-dmodel64",
    config={
        "model": "BERT4Rec", "max_len": MAX_LEN, "d_model": 64, "n_heads": 2, "n_layers": 2,
        "dropout": 0.2, "emb_dropout": 0.5, "mask_prob": MASK_PROB, "batch_size": BATCH_SIZE,
        "lr": optimizer.param_groups[0]['lr'], "weight_decay": optimizer.param_groups[0]['weight_decay'],
    }
)

EPOCHS = 60
PATIENCE = 5
MIN_DELTA = 0.0
MIN_EPOCHS_BEFORE_STOPPING = 10
WARMUP_EPOCHS = 5
best_val_map = -float('inf')
patience_counter = 0
best_state = None

mask_rng = np.random.default_rng(42)  # separate RNG for masking, seeded but advances each epoch (dynamic masking)

for epoch in range(EPOCHS):
    # --- Rebuild masked training batch fresh every epoch: dynamic masking is what makes
    # BERT4Rec training effective — reusing one static mask pattern is much weaker ---
    X_train_bert, Y_train_bert = build_bert4rec_training_batch(train_sequences, max_len=MAX_LEN,
                                                                  mask_prob=MASK_PROB, rng=mask_rng)
    train_loader_bert = DataLoader(
        torch.utils.data.TensorDataset(torch.tensor(X_train_bert, dtype=torch.long), torch.tensor(Y_train_bert, dtype=torch.long)),
        batch_size=BATCH_SIZE, shuffle=True
    )

    model.train()
    train_loss = 0.0
    total_grad_norm = 0.0

    for x_batch, y_batch in train_loader_bert:
        x_batch, y_batch = x_batch.to(device), y_batch.to(device)
        optimizer.zero_grad()
        hidden = model(x_batch)

        hidden_flat = hidden.view(-1, hidden.size(-1))
        targets_flat = y_batch.view(-1)
        mask = targets_flat != 0          # only positions that were actually masked contribute to loss
        hidden_valid = hidden_flat[mask]
        targets_valid = targets_flat[mask]

        logits, labels = sampled_logits_and_labels(model, hidden_valid, targets_valid, NUM_ITEMS, num_negatives=100)
        loss = criterion(logits, labels)
        loss.backward()

        grad_norm = torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=2.0)
        total_grad_norm += grad_norm.item()

        optimizer.step()
        train_loss += loss.item()

    train_loss /= len(train_loader_bert)
    avg_grad_norm = total_grad_norm / len(train_loader_bert)

    # --- Validation: leave-one-out via appended [MASK], take hidden[:, -1, :] (the MASK position) ---
    model.eval()
    val_loss = 0.0
    all_hidden, all_targets = [], []

    with torch.no_grad():
        for x_batch, y_batch in val_loader_bert:
            x_batch, y_batch = x_batch.to(device), y_batch.to(device)
            hidden = model(x_batch)

            hidden_valid = hidden[:, -1, :]   # last position = [MASK] position, by construction
            targets_valid = y_batch

            all_hidden.append(hidden_valid.cpu())
            all_targets.append(targets_valid.cpu())

            logits, labels = sampled_logits_and_labels(model, hidden_valid, targets_valid, NUM_ITEMS, num_negatives=100)
            loss = criterion(logits, labels)
            val_loss += loss.item()

    val_loss /= len(val_loader_bert)

    all_hidden = torch.cat(all_hidden).to(device)
    all_targets = torch.cat(all_targets).to(device)
    val_map5 = sampled_ranking_map_at_k(model, all_hidden, all_targets, NUM_ITEMS, num_negatives=999, k=5, seed=42)

    all_hidden_train_eval, all_targets_train_eval = [], []
    with torch.no_grad():
        for x_batch, y_batch in train_eval_loader_bert:
            x_batch, y_batch = x_batch.to(device), y_batch.to(device)
            hidden = model(x_batch)
            all_hidden_train_eval.append(hidden[:, -1, :].cpu())
            all_targets_train_eval.append(y_batch.cpu())

    all_hidden_train_eval = torch.cat(all_hidden_train_eval).to(device)
    all_targets_train_eval = torch.cat(all_targets_train_eval).to(device)
    train_map5 = sampled_ranking_map_at_k(model, all_hidden_train_eval, all_targets_train_eval, NUM_ITEMS, num_negatives=999, k=5, seed=42)

    scheduler.step(val_loss)
    current_lr = optimizer.param_groups[0]['lr']

    wandb.log({
        "epoch": epoch + 1, "train_loss": train_loss, "val_loss": val_loss,
        "grad_norm": avg_grad_norm, "learning_rate": current_lr,
        "val_map@5": val_map5, "train_map@5": train_map5,
        "overfit_gap_map@5": train_map5 - val_map5,
    })

    print(f"Epoch [{epoch+1}/{EPOCHS}] Train Loss: {train_loss:.4f} | Val Loss: {val_loss:.4f} | "
          f"Train MAP@5: {train_map5:.4f} | Val MAP@5: {val_map5:.4f} | "
          f"Gap: {train_map5 - val_map5:.4f} | Grad Norm: {avg_grad_norm:.4f}")

    if epoch + 1 > WARMUP_EPOCHS and val_map5 > best_val_map + MIN_DELTA:
        best_val_map = val_map5
        best_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}
        patience_counter = 0
    else:
        patience_counter += 1
        if epoch + 1 >= MIN_EPOCHS_BEFORE_STOPPING and patience_counter >= PATIENCE:
            print(f"Early stopping at epoch {epoch+1}")
            break

model.load_state_dict(best_state)
wandb.finish()

Epoch [1/60] Train Loss: 6.9797 | Val Loss: 4.6190 | Train MAP@5: 0.0068 | Val MAP@5: 0.0056 | Gap: 0.0012 | Grad Norm: 1.8282
Epoch [2/60] Train Loss: 4.5134 | Val Loss: 4.5774 | Train MAP@5: 0.0223 | Val MAP@5: 0.0194 | Gap: 0.0029 | Grad Norm: 0.3293
Epoch [3/60] Train Loss: 4.3416 | Val Loss: 4.2535 | Train MAP@5: 0.0558 | Val MAP@5: 0.0508 | Gap: 0.0050 | Grad Norm: 0.2343
Epoch [4/60] Train Loss: 4.2019 | Val Loss: 4.1888 | Train MAP@5: 0.0590 | Val MAP@5: 0.0541 | Gap: 0.0050 | Grad Norm: 0.2476
Epoch [5/60] Train Loss: 4.1193 | Val Loss: 4.1133 | Train MAP@5: 0.0662 | Val MAP@5: 0.0607 | Gap: 0.0055 | Grad Norm: 0.3515
Epoch [6/60] Train Loss: 4.0155 | Val Loss: 4.0728 | Train MAP@5: 0.0676 | Val MAP@5: 0.0616 | Gap: 0.0060 | Grad Norm: 0.5335
Epoch [7/60] Train Loss: 3.9454 | Val Loss: 4.0327 | Train MAP@5: 0.0723 | Val MAP@5: 0.0657 | Gap: 0.0066 | Grad Norm: 0.7039
Epoch [8/60] Train Loss: 3.8659 | Val Loss: 3.9990 | Train MAP@5: 0.0765 | Val MAP@5: 0.0685 | Gap: 0.0080 | Grad Norm: 0.8668
Epoch [9/60] Train Loss: 3.7959 | Val Loss: 3.9694 | Train MAP@5: 0.0801 | Val MAP@5: 0.0705 | Gap: 0.0096 | Grad Norm: 1.0259
Epoch [10/60] Train Loss: 3.7270 | Val Loss: 3.8894 | Train MAP@5: 0.0902 | Val MAP@5: 0.0801 | Gap: 0.0101 | Grad Norm: 1.1276
Epoch [11/60] Train Loss: 3.6706 | Val Loss: 3.8975 | Train MAP@5: 0.0914 | Val MAP@5: 0.0803 | Gap: 0.0111 | Grad Norm: 1.2406
Epoch [12/60] Train Loss: 3.6114 | Val Loss: 3.8113 | Train MAP@5: 0.0989 | Val MAP@5: 0.0867 | Gap: 0.0122 | Grad Norm: 1.3394
Epoch [13/60] Train Loss: 3.5594 | Val Loss: 3.8308 | Train MAP@5: 0.0994 | Val MAP@5: 0.0848 | Gap: 0.0146 | Grad Norm: 1.4019
Epoch [14/60] Train Loss: 3.5166 | Val Loss: 3.7863 | Train MAP@5: 0.1052 | Val MAP@5: 0.0906 | Gap: 0.0146 | Grad Norm: 1.4445
Epoch [15/60] Train Loss: 3.4903 | Val Loss: 3.7731 | Train MAP@5: 0.1080 | Val MAP@5: 0.0913 | Gap: 0.0167 | Grad Norm: 1.4960
Epoch [16/60] Train Loss: 3.4550 | Val Loss: 3.5981 | Train MAP@5: 0.1269 | Val MAP@5: 0.1122 | Gap: 0.0147 | Grad Norm: 1.5641
Epoch [17/60] Train Loss: 3.4096 | Val Loss: 3.5682 | Train MAP@5: 0.1365 | Val MAP@5: 0.1201 | Gap: 0.0165 | Grad Norm: 1.7299
Epoch [18/60] Train Loss: 3.3729 | Val Loss: 3.5258 | Train MAP@5: 0.1433 | Val MAP@5: 0.1255 | Gap: 0.0177 | Grad Norm: 1.7954
Epoch [19/60] Train Loss: 3.3424 | Val Loss: 3.5023 | Train MAP@5: 0.1484 | Val MAP@5: 0.1286 | Gap: 0.0198 | Grad Norm: 1.8349
Epoch [20/60] Train Loss: 3.3250 | Val Loss: 3.5103 | Train MAP@5: 0.1497 | Val MAP@5: 0.1291 | Gap: 0.0206 | Grad Norm: 1.8993
Epoch [21/60] Train Loss: 3.3092 | Val Loss: 3.4749 | Train MAP@5: 0.1546 | Val MAP@5: 0.1350 | Gap: 0.0196 | Grad Norm: 1.8966
Epoch [22/60] Train Loss: 3.2969 | Val Loss: 3.4800 | Train MAP@5: 0.1551 | Val MAP@5: 0.1342 | Gap: 0.0209 | Grad Norm: 1.9399
Epoch [23/60] Train Loss: 3.2801 | Val Loss: 3.4520 | Train MAP@5: 0.1615 | Val MAP@5: 0.1396 | Gap: 0.0219 | Grad Norm: 1.9463
Epoch [24/60] Train Loss: 3.2674 | Val Loss: 3.4535 | Train MAP@5: 0.1628 | Val MAP@5: 0.1384 | Gap: 0.0244 | Grad Norm: 1.9662
Epoch [25/60] Train Loss: 3.2608 | Val Loss: 3.4388 | Train MAP@5: 0.1644 | Val MAP@5: 0.1402 | Gap: 0.0242 | Grad Norm: 1.9778
Epoch [26/60] Train Loss: 3.2500 | Val Loss: 3.4580 | Train MAP@5: 0.1624 | Val MAP@5: 0.1376 | Gap: 0.0248 | Grad Norm: 1.9986
Epoch [27/60] Train Loss: 3.2412 | Val Loss: 3.4297 | Train MAP@5: 0.1657 | Val MAP@5: 0.1416 | Gap: 0.0241 | Grad Norm: 2.0083
Epoch [28/60] Train Loss: 3.2337 | Val Loss: 3.4246 | Train MAP@5: 0.1715 | Val MAP@5: 0.1443 | Gap: 0.0272 | Grad Norm: 2.0227
Epoch [29/60] Train Loss: 3.2254 | Val Loss: 3.4018 | Train MAP@5: 0.1710 | Val MAP@5: 0.1446 | Gap: 0.0264 | Grad Norm: 2.0216
Epoch [30/60] Train Loss: 3.2155 | Val Loss: 3.3983 | Train MAP@5: 0.1737 | Val MAP@5: 0.1469 | Gap: 0.0268 | Grad Norm: 2.0260
Epoch [31/60] Train Loss: 3.2126 | Val Loss: 3.4002 | Train MAP@5: 0.1744 | Val MAP@5: 0.1467 | Gap: 0.0277 | Grad Norm: 2.0081
Epoch [32/60] Train Loss: 3.2039 | Val Loss: 3.4075 | Train MAP@5: 0.1740 | Val MAP@5: 0.1458 | Gap: 0.0283 | Grad Norm: 2.0061
Epoch [33/60] Train Loss: 3.1083 | Val Loss: 3.3280 | Train MAP@5: 0.1919 | Val MAP@5: 0.1598 | Gap: 0.0321 | Grad Norm: 2.0635
Epoch [34/60] Train Loss: 3.0538 | Val Loss: 3.2925 | Train MAP@5: 0.1926 | Val MAP@5: 0.1612 | Gap: 0.0314 | Grad Norm: 2.1945
Epoch [35/60] Train Loss: 3.0276 | Val Loss: 3.2860 | Train MAP@5: 0.1978 | Val MAP@5: 0.1631 | Gap: 0.0347 | Grad Norm: 2.2910
Epoch [36/60] Train Loss: 3.0182 | Val Loss: 3.2865 | Train MAP@5: 0.1972 | Val MAP@5: 0.1618 | Gap: 0.0354 | Grad Norm: 2.4024
Epoch [37/60] Train Loss: 3.0132 | Val Loss: 3.2704 | Train MAP@5: 0.2006 | Val MAP@5: 0.1645 | Gap: 0.0361 | Grad Norm: 2.4865
Epoch [38/60] Train Loss: 3.0061 | Val Loss: 3.2763 | Train MAP@5: 0.2007 | Val MAP@5: 0.1635 | Gap: 0.0371 | Grad Norm: 2.5727
Epoch [39/60] Train Loss: 3.0022 | Val Loss: 3.2665 | Train MAP@5: 0.2015 | Val MAP@5: 0.1644 | Gap: 0.0372 | Grad Norm: 2.6408
Epoch [40/60] Train Loss: 3.0023 | Val Loss: 3.2892 | Train MAP@5: 0.2006 | Val MAP@5: 0.1623 | Gap: 0.0383 | Grad Norm: 2.6986
Epoch [41/60] Train Loss: 3.0011 | Val Loss: 3.2610 | Train MAP@5: 0.2036 | Val MAP@5: 0.1660 | Gap: 0.0376 | Grad Norm: 2.7544
Epoch [42/60] Train Loss: 2.9976 | Val Loss: 3.2752 | Train MAP@5: 0.2025 | Val MAP@5: 0.1658 | Gap: 0.0367 | Grad Norm: 2.8182
Epoch [43/60] Train Loss: 2.9999 | Val Loss: 3.2876 | Train MAP@5: 0.2000 | Val MAP@5: 0.1619 | Gap: 0.0381 | Grad Norm: 2.8505
Epoch [44/60] Train Loss: 2.9330 | Val Loss: 3.2318 | Train MAP@5: 0.2128 | Val MAP@5: 0.1717 | Gap: 0.0410 | Grad Norm: 2.8378
Epoch [45/60] Train Loss: 2.8979 | Val Loss: 3.2069 | Train MAP@5: 0.2177 | Val MAP@5: 0.1753 | Gap: 0.0424 | Grad Norm: 2.9419
Epoch [46/60] Train Loss: 2.8791 | Val Loss: 3.1974 | Train MAP@5: 0.2212 | Val MAP@5: 0.1766 | Gap: 0.0446 | Grad Norm: 3.0147
Epoch [47/60] Train Loss: 2.8682 | Val Loss: 3.1846 | Train MAP@5: 0.2206 | Val MAP@5: 0.1770 | Gap: 0.0436 | Grad Norm: 3.1199
Epoch [48/60] Train Loss: 2.8581 | Val Loss: 3.1852 | Train MAP@5: 0.2243 | Val MAP@5: 0.1789 | Gap: 0.0453 | Grad Norm: 3.1990
Epoch [49/60] Train Loss: 2.8546 | Val Loss: 3.1779 | Train MAP@5: 0.2244 | Val MAP@5: 0.1795 | Gap: 0.0449 | Grad Norm: 3.2942
Epoch [50/60] Train Loss: 2.8510 | Val Loss: 3.1840 | Train MAP@5: 0.2246 | Val MAP@5: 0.1782 | Gap: 0.0464 | Grad Norm: 3.3674
Epoch [51/60] Train Loss: 2.8506 | Val Loss: 3.1632 | Train MAP@5: 0.2255 | Val MAP@5: 0.1802 | Gap: 0.0453 | Grad Norm: 3.4526
Epoch [52/60] Train Loss: 2.8464 | Val Loss: 3.1746 | Train MAP@5: 0.2256 | Val MAP@5: 0.1800 | Gap: 0.0456 | Grad Norm: 3.5242
Epoch [53/60] Train Loss: 2.8474 | Val Loss: 3.1941 | Train MAP@5: 0.2232 | Val MAP@5: 0.1772 | Gap: 0.0461 | Grad Norm: 3.5779
Epoch [54/60] Train Loss: 2.8090 | Val Loss: 3.1608 | Train MAP@5: 0.2297 | Val MAP@5: 0.1819 | Gap: 0.0478 | Grad Norm: 3.5401
Epoch [55/60] Train Loss: 2.7924 | Val Loss: 3.1484 | Train MAP@5: 0.2339 | Val MAP@5: 0.1856 | Gap: 0.0483 | Grad Norm: 3.6030
Epoch [56/60] Train Loss: 2.7822 | Val Loss: 3.1397 | Train MAP@5: 0.2348 | Val MAP@5: 0.1864 | Gap: 0.0484 | Grad Norm: 3.6572
Epoch [57/60] Train Loss: 2.7724 | Val Loss: 3.1266 | Train MAP@5: 0.2342 | Val MAP@5: 0.1870 | Gap: 0.0472 | Grad Norm: 3.7100
Epoch [58/60] Train Loss: 2.7705 | Val Loss: 3.1305 | Train MAP@5: 0.2372 | Val MAP@5: 0.1877 | Gap: 0.0495 | Grad Norm: 3.7739
Epoch [59/60] Train Loss: 2.7672 | Val Loss: 3.1290 | Train MAP@5: 0.2350 | Val MAP@5: 0.1863 | Gap: 0.0487 | Grad Norm: 3.8346
Epoch [60/60] Train Loss: 2.7461 | Val Loss: 3.1153 | Train MAP@5: 0.2402 | Val MAP@5: 0.1897 | Gap: 0.0505 | Grad Norm: 3.7958

## Validate on test set

In [30]:
test_combined = pd.concat([train_df, valid_df, test_df])
test_sequences = build_user_sequences(test_combined)

X_test_bert, y_test = build_bert4rec_eval_batch(test_sequences, max_len=MAX_LEN)
print(f"Test: X={X_test_bert.shape}, y={len(y_test)}")

model.eval()
test_loader_bert = DataLoader(
    torch.utils.data.TensorDataset(torch.tensor(X_test_bert, dtype=torch.long), torch.tensor(y_test, dtype=torch.long)),
    batch_size=BATCH_SIZE, shuffle=False
)

all_hidden_test, all_targets_test = [], []
with torch.no_grad():
    for x_batch, y_batch in test_loader_bert:
        x_batch = x_batch.to(device)
        hidden = model(x_batch)
        all_hidden_test.append(hidden[:, -1, :].cpu())   # [MASK] position
        all_targets_test.append(y_batch)

all_hidden_test = torch.cat(all_hidden_test).to(device)
all_targets_test = torch.cat(all_targets_test).to(device)
print(f"all_hidden_test: {all_hidden_test.shape}, all_targets_test: {all_targets_test.shape}")

Test: X=(127184, 50), y=127184
all_hidden_test: torch.Size([127184, 64]), all_targets_test: torch.Size([127184])

In [31]:
@torch.no_grad()
def full_ranking_eval_bert4rec(model, hidden_all, targets_all, num_items, k_list=(5, 10), chunk_size=2048):
    """Same as full_ranking_eval, but restricts candidate embeddings to real items only
    (model.item_emb.weight has num_items+1 rows; the last row is [MASK] and must never
    be a recommendation candidate)."""
    max_k = max(k_list)
    all_item_emb = model.real_item_embeddings()   # shape (num_items, d_model) — MASK row excluded
    recommended_items_by_user = {}
    relevant_items_by_user = {}
    global_idx = 0

    for start in range(0, hidden_all.size(0), chunk_size):
        end = start + chunk_size
        hidden_chunk = hidden_all[start:end]
        targets_chunk = targets_all[start:end]

        logits_chunk = hidden_chunk @ all_item_emb.T

        target_domain_id_chunk = domain_id[targets_chunk]
        wrong_domain_mask = domain_id.unsqueeze(0) != target_domain_id_chunk.unsqueeze(1)
        logits_chunk = logits_chunk.masked_fill(wrong_domain_mask, float('-inf'))

        top_k_items = logits_chunk.topk(max_k, dim=1).indices

        for i in range(hidden_chunk.size(0)):
            recommended_items_by_user[global_idx] = top_k_items[i].tolist()
            relevant_items_by_user[global_idx] = [targets_chunk[i].item()]
            global_idx += 1

    return recommended_items_by_user, relevant_items_by_user

recommended_model, relevant_items = full_ranking_eval_bert4rec(model, all_hidden_test, all_targets_test, NUM_ITEMS, chunk_size=128)

model_metrics = {
    "MAP@5": map_at_k(recommended_model, relevant_items, k=5),
    "NDCG@10": average_metric_over_users(ndcg_at_k, recommended_model, relevant_items, k=10),
    "Recall@10": average_metric_over_users(recall_at_k, recommended_model, relevant_items, k=10),
}
print("Model:", model_metrics)

Model: {'MAP@5': 0.011351794775024113, 'NDCG@10': np.float64(0.01839898015127067), 'Recall@10': 0.035822115989432635}

In [32]:
# Rebuild baselines specifically against BERT4Rec's y_test ordering, to guarantee alignment
rng = np.random.default_rng(42)
recommended_popular_bert = {}
recommended_random_bert = {}
for i, target_item in enumerate(y_test):
    is_books_target = item_domain[target_item] == 'books'
    recommended_popular_bert[i] = top_popular_books if is_books_target else top_popular_movies
    pool = books_item_idx_np if is_books_target else movies_item_idx_np
    recommended_random_bert[i] = rng.choice(pool, size=10, replace=False).tolist()

In [33]:
# --- Domain-split results for BERT4Rec (same format as SASRec's domain breakdown) ---
# Reuses recommended_model / relevant_items produced by full_ranking_eval_bert4rec above,
# and the same recommended_popular / recommended_random baselines (domain-restricted,
# built once from y_test — valid for any model, since they don't depend on model predictions).

books_users, movies_users = split_by_domain(relevant_items, item_domain)
print(f"Books users: {len(books_users)}, Movies users: {len(movies_users)}")

results_by_domain_bert4rec = {}
for domain_name, user_ids in (("Books", books_users), ("Movies", movies_users)):
    model_d = compute_metrics_for_subset(recommended_model, relevant_items, user_ids)
    popular_d = compute_metrics_for_subset(recommended_popular_bert, relevant_items, user_ids)
    random_d = compute_metrics_for_subset(recommended_random_bert, relevant_items, user_ids)

    rows = []
    for metric in model_d:
        model_val = model_d[metric]
        popular_val = popular_d[metric]
        random_val = random_d[metric]
        lift_popular = model_val / popular_val if popular_val > 0 else float('inf')
        lift_random = model_val / random_val if random_val > 0 else float('inf')
        rows.append({
            "Metric": metric,
            "Model": model_val,
            "Top-Popular": popular_val,
            "Random": random_val,
            "Lift vs Popular": lift_popular,
            "Lift vs Random": lift_random,
        })

    df_domain = pd.DataFrame(rows)
    formatted = df_domain.copy()
    for col in ["Model", "Top-Popular", "Random"]:
        formatted[col] = formatted[col].map(lambda v: f"{v:.6f}")
    for col in ["Lift vs Popular", "Lift vs Random"]:
        formatted[col] = formatted[col].map(lambda v: "∞" if v == float('inf') else f"×{v:.2f}")

    print(f"\n=== {domain_name} (BERT4Rec) ===")
    print(formatted.to_string(index=False))
    results_by_domain_bert4rec[domain_name] = df_domain

Books users: 63034, Movies users: 64150

=== Books (BERT4Rec) ===
   Metric    Model Top-Popular   Random Lift vs Popular Lift vs Random
    MAP@5 0.010156    0.001262 0.000045           ×8.05        ×223.32
  NDCG@10 0.016497    0.002172 0.000064           ×7.59        ×257.67
Recall@10 0.032252    0.004347 0.000111           ×7.42        ×290.43

=== Movies (BERT4Rec) ===
   Metric    Model Top-Popular   Random Lift vs Popular Lift vs Random
    MAP@5 0.012527    0.002397 0.000029           ×5.23        ×430.49
  NDCG@10 0.020268    0.003810 0.000055           ×5.32        ×366.68
Recall@10 0.039330    0.007654 0.000125           ×5.14        ×315.38

## Training on single-domain

In [34]:
def build_single_domain_bert4rec_training_batch(user_sequences, num_items, mask_token, max_len=MAX_LEN, mask_prob=MASK_PROB, rng=None):
    """Same as build_bert4rec_training_batch, but num_items/mask_token are
    explicit params instead of reading the global NUM_ITEMS/MASK_TOKEN --
    those belong to the joint vocab, not a single-domain one."""
    rng = rng or np.random.default_rng()
    X, Y = [], []
    for seq in user_sequences.values():
        if len(seq) < 2:
            continue
        seq = seq[-max_len:] if len(seq) > max_len else seq
        pad = max_len - len(seq)
        inp = [0] * pad + list(seq)
        tgt = [0] * max_len

        real_positions = list(range(pad, max_len))
        n_mask = max(1, int(round(len(real_positions) * mask_prob)))
        mask_positions = rng.choice(real_positions, size=min(n_mask, len(real_positions)), replace=False)

        for i in mask_positions:
            tgt[i] = inp[i]
            r = rng.random()
            if r < 0.8:
                inp[i] = mask_token
            elif r < 0.9:
                inp[i] = int(rng.integers(1, num_items))
        X.append(inp)
        Y.append(tgt)
    return np.array(X), np.array(Y)


def sampled_logits_and_labels_single_domain(model, hidden_valid, targets_valid, num_items, num_negatives=100):
    """Same as sampled_logits_and_labels, but WITHOUT domain-restricted negative
    sampling -- the original hardcodes the global domain_id/books_item_idx/
    movies_item_idx tensors, which index out of bounds against a smaller
    single-domain model's embedding table."""
    N = hidden_valid.size(0)
    device = hidden_valid.device

    neg_items = torch.randint(1, num_items, (N, num_negatives), device=device)
    collision = neg_items == targets_valid.unsqueeze(1)
    if collision.any():
        neg_items[collision] = torch.randint(1, num_items, (int(collision.sum().item()),), device=device)

    candidates = torch.cat([targets_valid.unsqueeze(1), neg_items], dim=1)
    cand_emb = model.item_emb(candidates)
    logits = torch.bmm(cand_emb, hidden_valid.unsqueeze(-1)).squeeze(-1)
    labels = torch.zeros(N, dtype=torch.long, device=device)
    return logits, labels


@torch.no_grad()
def sampled_ranking_map_at_k_single_domain(model, hidden_all, targets_all, num_items, num_negatives=999, k=5, seed=42, chunk_size=2048):
    """Same as sampled_ranking_map_at_k, without domain-restricted sampling."""
    model.eval()
    device = hidden_all.device
    generator = torch.Generator(device=device).manual_seed(seed)

    recommended_items_by_user, relevant_items_by_user = {}, {}
    global_idx = 0

    for start in range(0, hidden_all.size(0), chunk_size):
        end = start + chunk_size
        hidden_chunk = hidden_all[start:end]
        targets_chunk = targets_all[start:end]
        n = hidden_chunk.size(0)

        neg_items = torch.randint(1, num_items, (n, num_negatives), device=device, generator=generator)
        collision = neg_items == targets_chunk.unsqueeze(1)
        if collision.any():
            n_coll = int(collision.sum().item())
            neg_items[collision] = torch.randint(1, num_items, (n_coll,), device=device, generator=generator)

        candidates = torch.cat([targets_chunk.unsqueeze(1), neg_items], dim=1)
        cand_emb = model.item_emb(candidates)
        logits = torch.bmm(cand_emb, hidden_chunk.unsqueeze(-1)).squeeze(-1)

        top_k_idx = logits.topk(k, dim=1).indices
        top_k_items = torch.gather(candidates, 1, top_k_idx)

        for i in range(n):
            recommended_items_by_user[global_idx] = top_k_items[i].tolist()
            relevant_items_by_user[global_idx] = [targets_chunk[i].item()]
            global_idx += 1

    return map_at_k(recommended_items_by_user, relevant_items_by_user, k=k)


@torch.no_grad()
def full_ranking_eval_bert4rec_single_domain(model, hidden_all, targets_all, num_items, k_list=(5, 10), chunk_size=2048):
    """Same as full_ranking_eval_bert4rec, minus the cross-domain masking --
    every item already belongs to the same domain here."""
    max_k = max(k_list)
    all_item_emb = model.real_item_embeddings()
    recommended_items_by_user, relevant_items_by_user = {}, {}
    global_idx = 0
    for start in range(0, hidden_all.size(0), chunk_size):
        end = start + chunk_size
        hidden_chunk = hidden_all[start:end]
        targets_chunk = targets_all[start:end]
        logits_chunk = hidden_chunk @ all_item_emb.T
        top_k_items = logits_chunk.topk(max_k, dim=1).indices
        for i in range(hidden_chunk.size(0)):
            recommended_items_by_user[global_idx] = top_k_items[i].tolist()
            relevant_items_by_user[global_idx] = [targets_chunk[i].item()]
            global_idx += 1
    return recommended_items_by_user, relevant_items_by_user


def train_bert4rec_single_domain(domain_name, raw_train_df, raw_valid_df, raw_test_df, epochs=60):
    print(f"\n{'='*20} BERT4Rec: {domain_name} {'='*20}")

    # Same MIN_ITEM_FREQ filter as the joint model (cell with frequent_items),
    # but computed within this domain alone -- the joint filter used cross-domain
    # combined counts, not valid for a single domain.
    train_df_d = raw_train_df.copy()
    valid_df_d = raw_valid_df.copy()
    test_df_d = raw_test_df.copy()
    counts = train_df_d['item_id'].value_counts()
    frequent = set(counts[counts >= MIN_ITEM_FREQ].index)
    train_df_d = train_df_d[train_df_d['item_id'].isin(frequent)].reset_index(drop=True)
    valid_df_d = valid_df_d[valid_df_d['item_id'].isin(frequent)].reset_index(drop=True)
    test_df_d = test_df_d[test_df_d['item_id'].isin(frequent)].reset_index(drop=True)

    domain_encoder = LabelEncoder()
    domain_encoder.fit(pd.concat([train_df_d['item_id'], valid_df_d['item_id'], test_df_d['item_id']]).unique())
    domain_num_items = len(domain_encoder.classes_) + 1
    domain_mask_token = domain_num_items
    for df in (train_df_d, valid_df_d, test_df_d):
        df['item_idx'] = domain_encoder.transform(df['item_id']) + 1

    train_sequences_d = build_user_sequences(train_df_d)
    valid_sequences_d = build_user_sequences(pd.concat([train_df_d, valid_df_d]))

    X_val, y_val = build_bert4rec_eval_batch(valid_sequences_d, max_len=MAX_LEN, mask_token=domain_mask_token)
    X_train_eval, y_train_eval = build_bert4rec_eval_batch(train_sequences_d, max_len=MAX_LEN, mask_token=domain_mask_token)
    val_loader_d = DataLoader(
        torch.utils.data.TensorDataset(torch.tensor(X_val, dtype=torch.long), torch.tensor(y_val, dtype=torch.long)),
        batch_size=BATCH_SIZE, shuffle=False)
    train_eval_loader_d = DataLoader(
        torch.utils.data.TensorDataset(torch.tensor(X_train_eval, dtype=torch.long), torch.tensor(y_train_eval, dtype=torch.long)),
        batch_size=BATCH_SIZE, shuffle=False)

    domain_model = BERT4Rec(num_items=domain_num_items, mask_token=domain_mask_token, max_len=MAX_LEN,
                             d_model=64, n_heads=2, n_layers=2, dropout=0.2, emb_dropout=0.5).to(device)
    domain_criterion = nn.CrossEntropyLoss(label_smoothing=0.1)
    domain_optimizer = torch.optim.Adam(domain_model.parameters(), lr=1e-3, weight_decay=1e-4)
    domain_scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(domain_optimizer, mode='min', patience=1, factor=0.5)

    wandb.init(
        project="recsys-sequential", name=f"bert4rec-{domain_name}-only-dmodel64",
        config={"model": "BERT4Rec", "domain": domain_name, "max_len": MAX_LEN, "d_model": 64,
                "n_heads": 2, "n_layers": 2, "dropout": 0.2, "emb_dropout": 0.5,
                "mask_prob": MASK_PROB, "batch_size": BATCH_SIZE},
    )

    PATIENCE, MIN_DELTA, MIN_EPOCHS_BEFORE_STOPPING, WARMUP_EPOCHS = 5, 0.0, 10, 5
    best_val_map, patience_counter, best_state = -float('inf'), 0, None
    mask_rng = np.random.default_rng(42)

    for epoch in range(epochs):
        X_train_bert, Y_train_bert = build_single_domain_bert4rec_training_batch(
            train_sequences_d, num_items=domain_num_items, mask_token=domain_mask_token,
            max_len=MAX_LEN, mask_prob=MASK_PROB, rng=mask_rng)
        train_loader_d = DataLoader(
            torch.utils.data.TensorDataset(torch.tensor(X_train_bert, dtype=torch.long), torch.tensor(Y_train_bert, dtype=torch.long)),
            batch_size=BATCH_SIZE, shuffle=True)

        domain_model.train()
        train_loss, total_grad_norm = 0.0, 0.0
        for x_batch, y_batch in train_loader_d:
            x_batch, y_batch = x_batch.to(device), y_batch.to(device)
            domain_optimizer.zero_grad()
            hidden = domain_model(x_batch)
            hidden_flat = hidden.view(-1, hidden.size(-1))
            targets_flat = y_batch.view(-1)
            mask = targets_flat != 0
            logits, labels = sampled_logits_and_labels_single_domain(domain_model, hidden_flat[mask], targets_flat[mask], domain_num_items, num_negatives=100)
            loss = domain_criterion(logits, labels)
            loss.backward()
            grad_norm = torch.nn.utils.clip_grad_norm_(domain_model.parameters(), max_norm=2.0)
            total_grad_norm += grad_norm.item()
            domain_optimizer.step()
            train_loss += loss.item()
        train_loss /= len(train_loader_d)
        avg_grad_norm = total_grad_norm / len(train_loader_d)

        domain_model.eval()
        val_loss = 0.0
        all_hidden, all_targets = [], []
        with torch.no_grad():
            for x_batch, y_batch in val_loader_d:
                x_batch, y_batch = x_batch.to(device), y_batch.to(device)
                hidden = domain_model(x_batch)
                hidden_valid, targets_valid = hidden[:, -1, :], y_batch
                all_hidden.append(hidden_valid.cpu())
                all_targets.append(targets_valid.cpu())
                logits, labels = sampled_logits_and_labels_single_domain(domain_model, hidden_valid, targets_valid, domain_num_items, num_negatives=100)
                val_loss += domain_criterion(logits, labels).item()
        val_loss /= len(val_loader_d)
        all_hidden, all_targets = torch.cat(all_hidden).to(device), torch.cat(all_targets).to(device)
        val_map5 = sampled_ranking_map_at_k_single_domain(domain_model, all_hidden, all_targets, domain_num_items, num_negatives=999, k=5, seed=42)

        all_hidden_te, all_targets_te = [], []
        with torch.no_grad():
            for x_batch, y_batch in train_eval_loader_d:
                x_batch = x_batch.to(device)
                hidden = domain_model(x_batch)
                all_hidden_te.append(hidden[:, -1, :].cpu())
                all_targets_te.append(y_batch)
        all_hidden_te, all_targets_te = torch.cat(all_hidden_te).to(device), torch.cat(all_targets_te).to(device)
        train_map5 = sampled_ranking_map_at_k_single_domain(domain_model, all_hidden_te, all_targets_te, domain_num_items, num_negatives=999, k=5, seed=42)

        domain_scheduler.step(val_loss)
        wandb.log({"epoch": epoch + 1, "train_loss": train_loss, "val_loss": val_loss,
                    "grad_norm": avg_grad_norm, "learning_rate": domain_optimizer.param_groups[0]['lr'],
                    "val_map@5": val_map5, "train_map@5": train_map5, "overfit_gap_map@5": train_map5 - val_map5})
        print(f"[{domain_name}] Epoch [{epoch+1}/{epochs}] Train Loss: {train_loss:.4f} | Val Loss: {val_loss:.4f} | "
              f"Train MAP@5: {train_map5:.4f} | Val MAP@5: {val_map5:.4f} | Gap: {train_map5 - val_map5:.4f}")

        if epoch + 1 > WARMUP_EPOCHS and val_map5 > best_val_map + MIN_DELTA:
            best_val_map = val_map5
            best_state = {k: v.cpu().clone() for k, v in domain_model.state_dict().items()}
            patience_counter = 0
        else:
            patience_counter += 1
            if epoch + 1 >= MIN_EPOCHS_BEFORE_STOPPING and patience_counter >= PATIENCE:
                print(f"[{domain_name}] Early stopping at epoch {epoch+1}")
                break

    domain_model.load_state_dict(best_state)
    wandb.finish()

    test_sequences_d = build_user_sequences(pd.concat([train_df_d, valid_df_d, test_df_d]))
    X_test, y_test_d = build_bert4rec_eval_batch(test_sequences_d, max_len=MAX_LEN, mask_token=domain_mask_token)
    domain_model.eval()
    test_loader_d = DataLoader(
        torch.utils.data.TensorDataset(torch.tensor(X_test, dtype=torch.long), torch.tensor(y_test_d, dtype=torch.long)),
        batch_size=BATCH_SIZE, shuffle=False)
    all_hidden_test, all_targets_test = [], []
    with torch.no_grad():
        for x_batch, y_batch in test_loader_d:
            hidden = domain_model(x_batch.to(device))
            all_hidden_test.append(hidden[:, -1, :].cpu())
            all_targets_test.append(y_batch)
    all_hidden_test, all_targets_test = torch.cat(all_hidden_test).to(device), torch.cat(all_targets_test).to(device)

    recommended_d, relevant_d = full_ranking_eval_bert4rec_single_domain(domain_model, all_hidden_test, all_targets_test, domain_num_items, chunk_size=128)
    model_metrics_d = {
        "MAP@5": map_at_k(recommended_d, relevant_d, k=5),
        "NDCG@10": average_metric_over_users(ndcg_at_k, recommended_d, relevant_d, k=10),
        "Recall@10": average_metric_over_users(recall_at_k, recommended_d, relevant_d, k=10),
    }

    real_items = np.arange(1, domain_num_items)
    top_popular_d = train_df_d['item_idx'].value_counts().index[:10].tolist()
    rng_bl = np.random.default_rng(42)
    recommended_popular_d = {i: top_popular_d for i in range(len(y_test_d))}
    recommended_random_d = {i: rng_bl.choice(real_items, size=10, replace=False).tolist() for i in range(len(y_test_d))}
    popular_metrics_d = {
        "MAP@5": map_at_k(recommended_popular_d, relevant_d, k=5),
        "NDCG@10": average_metric_over_users(ndcg_at_k, recommended_popular_d, relevant_d, k=10),
        "Recall@10": average_metric_over_users(recall_at_k, recommended_popular_d, relevant_d, k=10),
    }
    random_metrics_d = {
        "MAP@5": map_at_k(recommended_random_d, relevant_d, k=5),
        "NDCG@10": average_metric_over_users(ndcg_at_k, recommended_random_d, relevant_d, k=10),
        "Recall@10": average_metric_over_users(recall_at_k, recommended_random_d, relevant_d, k=10),
    }
    print(f"[{domain_name}] Model: {model_metrics_d} | Top-Popular: {popular_metrics_d} | Random: {random_metrics_d}")

    return model_metrics_d, popular_metrics_d, random_metrics_d, {
        'model': domain_model,
        'encoder': domain_encoder,
        'mask_token': domain_mask_token,
        'num_items': domain_num_items,
        'sequences': test_sequences_d,
    }

In [35]:
books_only_metrics, books_only_popular_metrics, books_only_random_metrics, books_only_bundle = train_bert4rec_single_domain(
    'books', books_train, books_valid, books_test, epochs=60,
)
movies_only_metrics, movies_only_popular_metrics, movies_only_random_metrics, movies_only_bundle = train_bert4rec_single_domain(
    'movies', movies_train, movies_valid, movies_test, epochs=60,
)

==================== BERT4Rec: books ====================

[books] Epoch [1/60] Train Loss: 7.2781 | Val Loss: 4.6213 | Train MAP@5: 0.0043 | Val MAP@5: 0.0040 | Gap: 0.0003
[books] Epoch [2/60] Train Loss: 4.5130 | Val Loss: 4.5928 | Train MAP@5: 0.0167 | Val MAP@5: 0.0164 | Gap: 0.0003
[books] Epoch [3/60] Train Loss: 4.4336 | Val Loss: 4.3278 | Train MAP@5: 0.0495 | Val MAP@5: 0.0476 | Gap: 0.0018
[books] Epoch [4/60] Train Loss: 4.3091 | Val Loss: 4.2449 | Train MAP@5: 0.0506 | Val MAP@5: 0.0492 | Gap: 0.0014
[books] Epoch [5/60] Train Loss: 4.2688 | Val Loss: 4.1971 | Train MAP@5: 0.0544 | Val MAP@5: 0.0528 | Gap: 0.0016
[books] Epoch [6/60] Train Loss: 4.2013 | Val Loss: 4.1049 | Train MAP@5: 0.0637 | Val MAP@5: 0.0625 | Gap: 0.0012
[books] Epoch [7/60] Train Loss: 4.1050 | Val Loss: 4.0503 | Train MAP@5: 0.0686 | Val MAP@5: 0.0646 | Gap: 0.0039
[books] Epoch [8/60] Train Loss: 4.0037 | Val Loss: 3.9701 | Train MAP@5: 0.0759 | Val MAP@5: 0.0708 | Gap: 0.0051
[books] Epoch [9/60] Train Loss: 3.8984 | Val Loss: 3.8881 | Train MAP@5: 0.0852 | Val MAP@5: 0.0774 | Gap: 0.0078
[books] Epoch [10/60] Train Loss: 3.8049 | Val Loss: 3.8331 | Train MAP@5: 0.0939 | Val MAP@5: 0.0839 | Gap: 0.0101
[books] Epoch [11/60] Train Loss: 3.7271 | Val Loss: 3.7894 | Train MAP@5: 0.1014 | Val MAP@5: 0.0894 | Gap: 0.0119
[books] Epoch [12/60] Train Loss: 3.6651 | Val Loss: 3.7641 | Train MAP@5: 0.1068 | Val MAP@5: 0.0923 | Gap: 0.0145
[books] Epoch [13/60] Train Loss: 3.6156 | Val Loss: 3.7312 | Train MAP@5: 0.1134 | Val MAP@5: 0.0969 | Gap: 0.0164
[books] Epoch [14/60] Train Loss: 3.5675 | Val Loss: 3.7122 | Train MAP@5: 0.1176 | Val MAP@5: 0.0989 | Gap: 0.0187
[books] Epoch [15/60] Train Loss: 3.5248 | Val Loss: 3.6668 | Train MAP@5: 0.1271 | Val MAP@5: 0.1055 | Gap: 0.0216
[books] Epoch [16/60] Train Loss: 3.4786 | Val Loss: 3.6265 | Train MAP@5: 0.1332 | Val MAP@5: 0.1104 | Gap: 0.0228
[books] Epoch [17/60] Train Loss: 3.4354 | Val Loss: 3.5976 | Train MAP@5: 0.1419 | Val MAP@5: 0.1152 | Gap: 0.0266
[books] Epoch [18/60] Train Loss: 3.3984 | Val Loss: 3.5714 | Train MAP@5: 0.1492 | Val MAP@5: 0.1190 | Gap: 0.0302
[books] Epoch [19/60] Train Loss: 3.3632 | Val Loss: 3.5646 | Train MAP@5: 0.1571 | Val MAP@5: 0.1233 | Gap: 0.0337
[books] Epoch [20/60] Train Loss: 3.3301 | Val Loss: 3.5214 | Train MAP@5: 0.1637 | Val MAP@5: 0.1279 | Gap: 0.0358
[books] Epoch [21/60] Train Loss: 3.3051 | Val Loss: 3.5180 | Train MAP@5: 0.1656 | Val MAP@5: 0.1281 | Gap: 0.0375
[books] Epoch [22/60] Train Loss: 3.2796 | Val Loss: 3.4983 | Train MAP@5: 0.1715 | Val MAP@5: 0.1318 | Gap: 0.0398
[books] Epoch [23/60] Train Loss: 3.2600 | Val Loss: 3.4789 | Train MAP@5: 0.1797 | Val MAP@5: 0.1363 | Gap: 0.0433
[books] Epoch [24/60] Train Loss: 3.2440 | Val Loss: 3.4651 | Train MAP@5: 0.1824 | Val MAP@5: 0.1388 | Gap: 0.0436
[books] Epoch [25/60] Train Loss: 3.2181 | Val Loss: 3.4414 | Train MAP@5: 0.1886 | Val MAP@5: 0.1423 | Gap: 0.0463
[books] Epoch [26/60] Train Loss: 3.1941 | Val Loss: 3.4070 | Train MAP@5: 0.1990 | Val MAP@5: 0.1502 | Gap: 0.0488
[books] Epoch [27/60] Train Loss: 3.1748 | Val Loss: 3.3827 | Train MAP@5: 0.2071 | Val MAP@5: 0.1554 | Gap: 0.0516
[books] Epoch [28/60] Train Loss: 3.1508 | Val Loss: 3.3574 | Train MAP@5: 0.2123 | Val MAP@5: 0.1607 | Gap: 0.0516
[books] Epoch [29/60] Train Loss: 3.1434 | Val Loss: 3.3541 | Train MAP@5: 0.2211 | Val MAP@5: 0.1644 | Gap: 0.0568
[books] Epoch [30/60] Train Loss: 3.1264 | Val Loss: 3.3404 | Train MAP@5: 0.2236 | Val MAP@5: 0.1643 | Gap: 0.0593
[books] Epoch [31/60] Train Loss: 3.1138 | Val Loss: 3.3208 | Train MAP@5: 0.2302 | Val MAP@5: 0.1693 | Gap: 0.0609
[books] Epoch [32/60] Train Loss: 3.1007 | Val Loss: 3.3036 | Train MAP@5: 0.2316 | Val MAP@5: 0.1716 | Gap: 0.0600
[books] Epoch [33/60] Train Loss: 3.0853 | Val Loss: 3.2957 | Train MAP@5: 0.2370 | Val MAP@5: 0.1749 | Gap: 0.0621
[books] Epoch [34/60] Train Loss: 3.0724 | Val Loss: 3.2784 | Train MAP@5: 0.2421 | Val MAP@5: 0.1780 | Gap: 0.0641
[books] Epoch [35/60] Train Loss: 3.0621 | Val Loss: 3.2796 | Train MAP@5: 0.2426 | Val MAP@5: 0.1767 | Gap: 0.0659
[books] Epoch [36/60] Train Loss: 3.0524 | Val Loss: 3.2581 | Train MAP@5: 0.2477 | Val MAP@5: 0.1813 | Gap: 0.0664
[books] Epoch [37/60] Train Loss: 3.0445 | Val Loss: 3.2602 | Train MAP@5: 0.2566 | Val MAP@5: 0.1865 | Gap: 0.0701
[books] Epoch [38/60] Train Loss: 3.0372 | Val Loss: 3.2482 | Train MAP@5: 0.2565 | Val MAP@5: 0.1845 | Gap: 0.0719
[books] Epoch [39/60] Train Loss: 3.0252 | Val Loss: 3.2590 | Train MAP@5: 0.2592 | Val MAP@5: 0.1847 | Gap: 0.0745
[books] Epoch [40/60] Train Loss: 3.0101 | Val Loss: 3.2415 | Train MAP@5: 0.2639 | Val MAP@5: 0.1887 | Gap: 0.0752
[books] Epoch [41/60] Train Loss: 3.0060 | Val Loss: 3.2256 | Train MAP@5: 0.2653 | Val MAP@5: 0.1908 | Gap: 0.0746
[books] Epoch [42/60] Train Loss: 3.0054 | Val Loss: 3.2238 | Train MAP@5: 0.2643 | Val MAP@5: 0.1897 | Gap: 0.0745
[books] Epoch [43/60] Train Loss: 2.9993 | Val Loss: 3.2175 | Train MAP@5: 0.2671 | Val MAP@5: 0.1915 | Gap: 0.0756
[books] Epoch [44/60] Train Loss: 2.9873 | Val Loss: 3.2074 | Train MAP@5: 0.2715 | Val MAP@5: 0.1956 | Gap: 0.0759
[books] Epoch [45/60] Train Loss: 2.9828 | Val Loss: 3.2083 | Train MAP@5: 0.2708 | Val MAP@5: 0.1946 | Gap: 0.0763
[books] Epoch [46/60] Train Loss: 2.9749 | Val Loss: 3.2163 | Train MAP@5: 0.2710 | Val MAP@5: 0.1931 | Gap: 0.0778
[books] Epoch [47/60] Train Loss: 2.8464 | Val Loss: 3.1311 | Train MAP@5: 0.3059 | Val MAP@5: 0.2148 | Gap: 0.0911
[books] Epoch [48/60] Train Loss: 2.7713 | Val Loss: 3.0980 | Train MAP@5: 0.3252 | Val MAP@5: 0.2253 | Gap: 0.0999
[books] Epoch [49/60] Train Loss: 2.7453 | Val Loss: 3.0788 | Train MAP@5: 0.3307 | Val MAP@5: 0.2277 | Gap: 0.1030
[books] Epoch [50/60] Train Loss: 2.7208 | Val Loss: 3.0717 | Train MAP@5: 0.3329 | Val MAP@5: 0.2288 | Gap: 0.1041
[books] Epoch [51/60] Train Loss: 2.7128 | Val Loss: 3.0605 | Train MAP@5: 0.3377 | Val MAP@5: 0.2308 | Gap: 0.1069
[books] Epoch [52/60] Train Loss: 2.7140 | Val Loss: 3.0550 | Train MAP@5: 0.3385 | Val MAP@5: 0.2318 | Gap: 0.1067
[books] Epoch [53/60] Train Loss: 2.7049 | Val Loss: 3.0535 | Train MAP@5: 0.3408 | Val MAP@5: 0.2333 | Gap: 0.1076
[books] Epoch [54/60] Train Loss: 2.7062 | Val Loss: 3.0575 | Train MAP@5: 0.3439 | Val MAP@5: 0.2343 | Gap: 0.1096
[books] Epoch [55/60] Train Loss: 2.7102 | Val Loss: 3.0576 | Train MAP@5: 0.3427 | Val MAP@5: 0.2343 | Gap: 0.1084
[books] Epoch [56/60] Train Loss: 2.6248 | Val Loss: 3.0201 | Train MAP@5: 0.3603 | Val MAP@5: 0.2447 | Gap: 0.1155
[books] Epoch [57/60] Train Loss: 2.5898 | Val Loss: 2.9981 | Train MAP@5: 0.3698 | Val MAP@5: 0.2494 | Gap: 0.1204
[books] Epoch [58/60] Train Loss: 2.5659 | Val Loss: 2.9807 | Train MAP@5: 0.3751 | Val MAP@5: 0.2527 | Gap: 0.1224
[books] Epoch [59/60] Train Loss: 2.5573 | Val Loss: 2.9782 | Train MAP@5: 0.3810 | Val MAP@5: 0.2553 | Gap: 0.1257
[books] Epoch [60/60] Train Loss: 2.5416 | Val Loss: 2.9656 | Train MAP@5: 0.3797 | Val MAP@5: 0.2556 | Gap: 0.1240

[books] Model: {'MAP@5': 0.015036538065676428, 'NDCG@10': np.float64(0.024178717098420767), 'Recall@10': 0.04683589560243118} | Top-Popular: {'MAP@5': 0.0017830251026532758, 'NDCG@10': np.float64(0.0028706673692041914), 'Recall@10': 0.005460395878701206} | Random: {'MAP@5': 2.97938267191038e-05, 'NDCG@10': np.float64(5.0340200214837516e-05), 'Recall@10': 9.750706926252153e-05}

==================== BERT4Rec: movies ====================

[movies] Epoch [1/60] Train Loss: 6.9853 | Val Loss: 4.5987 | Train MAP@5: 0.0176 | Val MAP@5: 0.0150 | Gap: 0.0026
[movies] Epoch [2/60] Train Loss: 4.4309 | Val Loss: 4.3269 | Train MAP@5: 0.0660 | Val MAP@5: 0.0619 | Gap: 0.0042
[movies] Epoch [3/60] Train Loss: 4.1714 | Val Loss: 4.0767 | Train MAP@5: 0.0739 | Val MAP@5: 0.0699 | Gap: 0.0040
[movies] Epoch [4/60] Train Loss: 4.0755 | Val Loss: 4.0109 | Train MAP@5: 0.0795 | Val MAP@5: 0.0755 | Gap: 0.0040
[movies] Epoch [5/60] Train Loss: 3.9539 | Val Loss: 3.8976 | Train MAP@5: 0.0849 | Val MAP@5: 0.0792 | Gap: 0.0058
[movies] Epoch [6/60] Train Loss: 3.8423 | Val Loss: 3.8289 | Train MAP@5: 0.0913 | Val MAP@5: 0.0847 | Gap: 0.0066
[movies] Epoch [7/60] Train Loss: 3.7587 | Val Loss: 3.7790 | Train MAP@5: 0.1000 | Val MAP@5: 0.0919 | Gap: 0.0080
[movies] Epoch [8/60] Train Loss: 3.6741 | Val Loss: 3.7350 | Train MAP@5: 0.1086 | Val MAP@5: 0.0990 | Gap: 0.0096
[movies] Epoch [9/60] Train Loss: 3.5965 | Val Loss: 3.6649 | Train MAP@5: 0.1190 | Val MAP@5: 0.1089 | Gap: 0.0100
[movies] Epoch [10/60] Train Loss: 3.5091 | Val Loss: 3.6505 | Train MAP@5: 0.1262 | Val MAP@5: 0.1112 | Gap: 0.0149
[movies] Epoch [11/60] Train Loss: 3.4348 | Val Loss: 3.5712 | Train MAP@5: 0.1372 | Val MAP@5: 0.1206 | Gap: 0.0166
[movies] Epoch [12/60] Train Loss: 3.3853 | Val Loss: 3.5757 | Train MAP@5: 0.1379 | Val MAP@5: 0.1196 | Gap: 0.0182
[movies] Epoch [13/60] Train Loss: 3.3427 | Val Loss: 3.5380 | Train MAP@5: 0.1463 | Val MAP@5: 0.1254 | Gap: 0.0209
[movies] Epoch [14/60] Train Loss: 3.3079 | Val Loss: 3.5041 | Train MAP@5: 0.1514 | Val MAP@5: 0.1292 | Gap: 0.0221
[movies] Epoch [15/60] Train Loss: 3.2807 | Val Loss: 3.4984 | Train MAP@5: 0.1543 | Val MAP@5: 0.1291 | Gap: 0.0251
[movies] Epoch [16/60] Train Loss: 3.2512 | Val Loss: 3.4808 | Train MAP@5: 0.1589 | Val MAP@5: 0.1346 | Gap: 0.0243
[movies] Epoch [17/60] Train Loss: 3.2287 | Val Loss: 3.4646 | Train MAP@5: 0.1614 | Val MAP@5: 0.1355 | Gap: 0.0260
[movies] Epoch [18/60] Train Loss: 3.2040 | Val Loss: 3.4828 | Train MAP@5: 0.1601 | Val MAP@5: 0.1322 | Gap: 0.0279
[movies] Epoch [19/60] Train Loss: 3.1859 | Val Loss: 3.4563 | Train MAP@5: 0.1643 | Val MAP@5: 0.1346 | Gap: 0.0296
[movies] Epoch [20/60] Train Loss: 3.1654 | Val Loss: 3.4474 | Train MAP@5: 0.1698 | Val MAP@5: 0.1390 | Gap: 0.0308
[movies] Epoch [21/60] Train Loss: 3.1592 | Val Loss: 3.4463 | Train MAP@5: 0.1701 | Val MAP@5: 0.1377 | Gap: 0.0324
[movies] Epoch [22/60] Train Loss: 3.1394 | Val Loss: 3.3375 | Train MAP@5: 0.1840 | Val MAP@5: 0.1542 | Gap: 0.0299
[movies] Epoch [23/60] Train Loss: 3.1128 | Val Loss: 3.2932 | Train MAP@5: 0.1965 | Val MAP@5: 0.1648 | Gap: 0.0317
[movies] Epoch [24/60] Train Loss: 3.0936 | Val Loss: 3.2824 | Train MAP@5: 0.1984 | Val MAP@5: 0.1673 | Gap: 0.0311
[movies] Epoch [25/60] Train Loss: 3.0860 | Val Loss: 3.2881 | Train MAP@5: 0.2002 | Val MAP@5: 0.1669 | Gap: 0.0333
[movies] Epoch [26/60] Train Loss: 3.0710 | Val Loss: 3.2476 | Train MAP@5: 0.2065 | Val MAP@5: 0.1751 | Gap: 0.0314
[movies] Epoch [27/60] Train Loss: 3.0596 | Val Loss: 3.2449 | Train MAP@5: 0.2085 | Val MAP@5: 0.1758 | Gap: 0.0327
[movies] Epoch [28/60] Train Loss: 3.0517 | Val Loss: 3.2425 | Train MAP@5: 0.2117 | Val MAP@5: 0.1767 | Gap: 0.0350
[movies] Epoch [29/60] Train Loss: 3.0415 | Val Loss: 3.2363 | Train MAP@5: 0.2147 | Val MAP@5: 0.1794 | Gap: 0.0353
[movies] Epoch [30/60] Train Loss: 3.0280 | Val Loss: 3.2206 | Train MAP@5: 0.2138 | Val MAP@5: 0.1797 | Gap: 0.0341
[movies] Epoch [31/60] Train Loss: 3.0192 | Val Loss: 3.2171 | Train MAP@5: 0.2193 | Val MAP@5: 0.1826 | Gap: 0.0367
[movies] Epoch [32/60] Train Loss: 3.0173 | Val Loss: 3.2098 | Train MAP@5: 0.2182 | Val MAP@5: 0.1813 | Gap: 0.0369
[movies] Epoch [33/60] Train Loss: 3.0019 | Val Loss: 3.2021 | Train MAP@5: 0.2204 | Val MAP@5: 0.1832 | Gap: 0.0372
[movies] Epoch [34/60] Train Loss: 2.9964 | Val Loss: 3.2002 | Train MAP@5: 0.2246 | Val MAP@5: 0.1860 | Gap: 0.0386
[movies] Epoch [35/60] Train Loss: 2.9900 | Val Loss: 3.1915 | Train MAP@5: 0.2247 | Val MAP@5: 0.1862 | Gap: 0.0385
[movies] Epoch [36/60] Train Loss: 2.9762 | Val Loss: 3.2002 | Train MAP@5: 0.2280 | Val MAP@5: 0.1874 | Gap: 0.0406
[movies] Epoch [37/60] Train Loss: 2.9757 | Val Loss: 3.1882 | Train MAP@5: 0.2291 | Val MAP@5: 0.1885 | Gap: 0.0405
[movies] Epoch [38/60] Train Loss: 2.9696 | Val Loss: 3.1993 | Train MAP@5: 0.2278 | Val MAP@5: 0.1855 | Gap: 0.0423
[movies] Epoch [39/60] Train Loss: 2.9643 | Val Loss: 3.1812 | Train MAP@5: 0.2286 | Val MAP@5: 0.1876 | Gap: 0.0409
[movies] Epoch [40/60] Train Loss: 2.9598 | Val Loss: 3.1811 | Train MAP@5: 0.2301 | Val MAP@5: 0.1877 | Gap: 0.0424
[movies] Epoch [41/60] Train Loss: 2.9636 | Val Loss: 3.1736 | Train MAP@5: 0.2336 | Val MAP@5: 0.1899 | Gap: 0.0437
[movies] Epoch [42/60] Train Loss: 2.9528 | Val Loss: 3.1812 | Train MAP@5: 0.2328 | Val MAP@5: 0.1875 | Gap: 0.0453
[movies] Epoch [43/60] Train Loss: 2.9487 | Val Loss: 3.1648 | Train MAP@5: 0.2357 | Val MAP@5: 0.1919 | Gap: 0.0439
[movies] Epoch [44/60] Train Loss: 2.9476 | Val Loss: 3.1794 | Train MAP@5: 0.2333 | Val MAP@5: 0.1899 | Gap: 0.0433
[movies] Epoch [45/60] Train Loss: 2.9431 | Val Loss: 3.1715 | Train MAP@5: 0.2375 | Val MAP@5: 0.1912 | Gap: 0.0463
[movies] Epoch [46/60] Train Loss: 2.8409 | Val Loss: 3.1197 | Train MAP@5: 0.2570 | Val MAP@5: 0.2021 | Gap: 0.0549
[movies] Epoch [47/60] Train Loss: 2.7951 | Val Loss: 3.0866 | Train MAP@5: 0.2643 | Val MAP@5: 0.2070 | Gap: 0.0573
[movies] Epoch [48/60] Train Loss: 2.7748 | Val Loss: 3.0868 | Train MAP@5: 0.2687 | Val MAP@5: 0.2088 | Gap: 0.0599
[movies] Epoch [49/60] Train Loss: 2.7664 | Val Loss: 3.0715 | Train MAP@5: 0.2705 | Val MAP@5: 0.2109 | Gap: 0.0596
[movies] Epoch [50/60] Train Loss: 2.7604 | Val Loss: 3.0741 | Train MAP@5: 0.2699 | Val MAP@5: 0.2088 | Gap: 0.0611
[movies] Epoch [51/60] Train Loss: 2.7561 | Val Loss: 3.0750 | Train MAP@5: 0.2696 | Val MAP@5: 0.2084 | Gap: 0.0613
[movies] Epoch [52/60] Train Loss: 2.7008 | Val Loss: 3.0447 | Train MAP@5: 0.2820 | Val MAP@5: 0.2162 | Gap: 0.0659
[movies] Epoch [53/60] Train Loss: 2.6705 | Val Loss: 3.0380 | Train MAP@5: 0.2865 | Val MAP@5: 0.2186 | Gap: 0.0679
[movies] Epoch [54/60] Train Loss: 2.6602 | Val Loss: 3.0286 | Train MAP@5: 0.2896 | Val MAP@5: 0.2205 | Gap: 0.0691
[movies] Epoch [55/60] Train Loss: 2.6489 | Val Loss: 3.0224 | Train MAP@5: 0.2914 | Val MAP@5: 0.2205 | Gap: 0.0709
[movies] Epoch [56/60] Train Loss: 2.6410 | Val Loss: 3.0150 | Train MAP@5: 0.2924 | Val MAP@5: 0.2214 | Gap: 0.0709
[movies] Epoch [57/60] Train Loss: 2.6359 | Val Loss: 3.0150 | Train MAP@5: 0.2922 | Val MAP@5: 0.2211 | Gap: 0.0711
[movies] Epoch [58/60] Train Loss: 2.6328 | Val Loss: 3.0137 | Train MAP@5: 0.2947 | Val MAP@5: 0.2212 | Gap: 0.0735
[movies] Epoch [59/60] Train Loss: 2.6302 | Val Loss: 3.0100 | Train MAP@5: 0.2958 | Val MAP@5: 0.2236 | Gap: 0.0721
[movies] Epoch [60/60] Train Loss: 2.6274 | Val Loss: 3.0096 | Train MAP@5: 0.2975 | Val MAP@5: 0.2226 | Gap: 0.0750

[movies] Model: {'MAP@5': 0.014553757595810946, 'NDCG@10': np.float64(0.024043585853325732), 'Recall@10': 0.04751288070966014} | Top-Popular: {'MAP@5': 0.004098980572581026, 'NDCG@10': np.float64(0.0064843998990559305), 'Recall@10': 0.013061906187467503} | Random: {'MAP@5': 5.304593988476951e-05, 'NDCG@10': np.float64(9.679746269952057e-05), 'Recall@10': 0.00020483085698079316}

## Saving metrics results

In [36]:
def bert4rec_result_row(model_name, column):
    """Mirrors sasrec_result_row -- reads the joint model's own
    domain-split results table (results_by_domain_bert4rec, built above),
    for the joint model / Top-Popular / Random rows. Was called below but
    never defined -- bert4rec_result_row_from_metrics (for the
    books_only/movies_only rows, which don't have a domain-split table of
    their own) was the only one actually written."""
    row = {
        'model': model_name,
        'd_model': 64, 'n_heads': 2, 'n_layers': 2, 'emb_dropout': 0.5,
        'k': 10, 'map_k': 5,
        'n_users': train_df['user_id'].nunique(),
        'n_items': NUM_ITEMS - 1,
    }
    for metric_label, key in [('MAP@5', 'map@5'), ('NDCG@10', 'ndcg@10'), ('Recall@10', 'recall@10')]:
        books_val = extract_metric(results_by_domain_bert4rec['Books'], column, metric_label)
        movies_val = extract_metric(results_by_domain_bert4rec['Movies'], column, metric_label)
        row[f'books_test_{key}'] = round(books_val, 4)
        row[f'movies_test_{key}'] = round(movies_val, 4)
        row[f'test_macro_{key}'] = round((books_val + movies_val) / 2, 4)
    return row


def bert4rec_result_row_from_metrics(model_name, metrics_dict):
    row = {
        'model': model_name, 'd_model': 64, 'n_heads': 2, 'n_layers': 2, 'emb_dropout': 0.5,
        'k': 10, 'map_k': 5, 'n_users': train_df['user_id'].nunique(), 'n_items': NUM_ITEMS - 1,
    }
    for metric_label, key in [('MAP@5', 'map@5'), ('NDCG@10', 'ndcg@10'), ('Recall@10', 'recall@10')]:
        row[f'test_{key}'] = round(metrics_dict[metric_label], 4)
    return row

bert4rec_metrics_results = pd.DataFrame([
    bert4rec_result_row('bert4rec_books_movies_joint', 'Model'),
    bert4rec_result_row_from_metrics('bert4rec_books_only', books_only_metrics),
    bert4rec_result_row_from_metrics('bert4rec_movies_only', movies_only_metrics),
    bert4rec_result_row('popularity_baseline', 'Top-Popular'),
    bert4rec_result_row('random_baseline', 'Random'),
])

RESULTS_DIR = f'{DATA_DIR}/results'
os.makedirs(RESULTS_DIR, exist_ok=True)
bert4rec_metrics_results.to_csv(f'{RESULTS_DIR}/bert4rec_metrics.csv', index=False)
bert4rec_metrics_results

,model,d_model,n_heads,n_layers,emb_dropout,k,map_k,n_users,n_items,books_test_map@5,...,test_macro_map@5,books_test_ndcg@10,movies_test_ndcg@10,test_macro_ndcg@10,books_test_recall@10,movies_test_recall@10,test_macro_recall@10,test_map@5,test_ndcg@10,test_recall@10
0,bert4rec_books_movies_joint,64,2,2,0.5,10,5,127183,190466,0.0102,...,0.0113,0.0165,0.0203,0.0184,0.0323,0.0393,0.0358,NaN,NaN,NaN
1,bert4rec_books_only,64,2,2,0.5,10,5,127183,190466,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0150,0.0242,0.0468
2,bert4rec_movies_only,64,2,2,0.5,10,5,127183,190466,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0146,0.0240,0.0475
3,popularity_baseline,64,2,2,0.5,10,5,127183,190466,0.0013,...,0.0018,0.0022,0.0038,0.0030,0.0043,0.0077,0.0060,NaN,NaN,NaN
4,random_baseline,64,2,2,0.5,10,5,127183,190466,0.0000,...,0.0000,0.0001,0.0001,0.0001,0.0001,0.0001,0.0001,NaN,NaN,NaN

## Export artifacts for the app MVP

In [37]:
import json

ARTIFACTS_DIR = f'{DATA_DIR}/artifacts/bert4rec'
os.makedirs(ARTIFACTS_DIR, exist_ok=True)

torch.save(model.state_dict(), f'{ARTIFACTS_DIR}/model_state_dict.pt')

# Same vocabulary as SASRec (both trained on the same encoder/train_df) --
# duplicated here so each artifact directory is self-contained.
item2idx = {cls: i + 1 for i, cls in enumerate(encoder.classes_)}
with open(f'{ARTIFACTS_DIR}/item2idx.json', 'w') as f:
    json.dump(item2idx, f)

with open(f'{ARTIFACTS_DIR}/domain_item_indices.json', 'w') as f:
    json.dump({
        'books': books_item_idx.cpu().tolist(),
        'movies': movies_item_idx.cpu().tolist(),
    }, f)

with open(f'{ARTIFACTS_DIR}/config.json', 'w') as f:
    json.dump({
        'num_items': NUM_ITEMS,
        'max_len': MAX_LEN,
        'mask_token': MASK_TOKEN,
        'd_model': 64,
        'n_heads': 2,
        'n_layers': 2,
        'dropout': 0.2,
        'emb_dropout': 0.5,
    }, f)

print(f'Saved BERT4Rec artifacts to {ARTIFACTS_DIR}')

Saved BERT4Rec artifacts to /content/drive/MyDrive/recsys-data/artifacts/bert4rec

## Export recs_bulk for single vs multi domain A/B test

Bulk top-10 recommendations per user, in the format `notebooks/a_b_test.ipynb` (`a-b-test` branch) reads: a JSON list of `{"user_id", "recommended_item_ids", "recommended_titles"}`. Exports both the joint (multi-domain) and single-domain BERT4Rec models, based on each user's *full known history* (train+valid+test), not a held-out target -- this is "what would we recommend right now", not an evaluation batch.

In [38]:
import json

books_meta = pd.read_csv(f'{DATA_DIR}/books_meta.csv')
movies_meta = pd.read_csv(f'{DATA_DIR}/movies_meta.csv')
books_title = books_meta.set_index('parent_asin')['title'].to_dict()
movies_title = movies_meta.set_index('parent_asin')['title'].to_dict()


def title_for(item_id):
    domain, asin = item_id.split('::', 1)
    lookup = books_title if domain == 'books' else movies_title
    return lookup.get(asin, '(title not found)')


def build_bert4rec_recommend_batch(user_sequences, max_len=MAX_LEN, mask_token=MASK_TOKEN):
    """Like build_bert4rec_eval_batch, but keeps user_id and doesn't hold out
    the last item -- full known history + a trailing [MASK] to predict what
    comes next, for generating real recommendations rather than evaluating
    against a held-out target."""
    user_ids, X = [], []
    for user_id, seq in user_sequences.items():
        if len(seq) < 1:
            continue
        hist = list(seq)
        if len(hist) >= max_len:
            hist = hist[-(max_len - 1):]
        seq_with_mask = hist + [mask_token]
        pad = max_len - len(seq_with_mask)
        user_ids.append(user_id)
        X.append([0] * pad + seq_with_mask)
    return user_ids, np.array(X)


@torch.no_grad()
def bulk_recommend_bert4rec_joint(target_domain, k=10, max_len=MAX_LEN, chunk_size=512):
    """Real per-user top-k recs from the joint BERT4Rec model, restricted to
    target_domain via the same domain masking full_ranking_eval_bert4rec uses,
    based on each user's full known history (test_sequences, already built
    above from train+valid+test)."""
    model.eval()
    user_ids, X = build_bert4rec_recommend_batch(test_sequences, max_len=max_len, mask_token=MASK_TOKEN)
    all_item_emb = model.real_item_embeddings()
    anchor_item = books_item_idx[0] if target_domain == 'books' else movies_item_idx[0]
    target_domain_id = domain_id[anchor_item]

    recommendations = {}
    for start in range(0, len(X), chunk_size):
        end = start + chunk_size
        x_batch = torch.tensor(X[start:end], dtype=torch.long, device=device)
        hidden = model(x_batch)[:, -1, :]
        logits = hidden @ all_item_emb.T
        wrong_domain_mask = domain_id != target_domain_id
        logits = logits.masked_fill(wrong_domain_mask.unsqueeze(0), float('-inf'))
        top_k = logits.topk(k, dim=1).indices
        for i, uid in enumerate(user_ids[start:end]):
            recommendations[uid] = top_k[i].tolist()
    return recommendations


@torch.no_grad()
def bulk_recommend_bert4rec_single_domain(bundle, k=10, max_len=MAX_LEN, chunk_size=512):
    """Same idea as bulk_recommend_bert4rec_joint, but for a single-domain
    bundle (see train_bert4rec_single_domain's return value) -- no domain
    masking needed, the whole vocabulary already belongs to one domain."""
    domain_model = bundle['model']
    domain_model.eval()
    user_ids, X = build_bert4rec_recommend_batch(bundle['sequences'], max_len=max_len, mask_token=bundle['mask_token'])
    all_item_emb = domain_model.real_item_embeddings()

    recommendations = {}
    for start in range(0, len(X), chunk_size):
        end = start + chunk_size
        x_batch = torch.tensor(X[start:end], dtype=torch.long, device=device)
        hidden = domain_model(x_batch)[:, -1, :]
        logits = hidden @ all_item_emb.T
        top_k = logits.topk(k, dim=1).indices
        for i, uid in enumerate(user_ids[start:end]):
            recommendations[uid] = top_k[i].tolist()
    return recommendations


def export_recs_bulk(recs, idx2item, save_path):
    bulk = [
        {
            'user_id': user_id,
            'recommended_item_ids': [idx2item[idx] for idx in item_indices],
            'recommended_titles': [title_for(idx2item[idx]) for idx in item_indices],
        }
        for user_id, item_indices in recs.items() if item_indices
    ]
    os.makedirs(os.path.dirname(save_path), exist_ok=True)
    with open(save_path, 'w') as f:
        json.dump(bulk, f)
    print(f"Saved {len(bulk)} users' recs to {save_path}")
    return bulk


AB_TEST_DIR = f'{DATA_DIR}/a-b-test'

idx2item_joint = {i + 1: cls for i, cls in enumerate(encoder.classes_)}
idx2item_books_only = {i + 1: cls for i, cls in enumerate(books_only_bundle['encoder'].classes_)}
idx2item_movies_only = {i + 1: cls for i, cls in enumerate(movies_only_bundle['encoder'].classes_)}

# Multi-domain (joint) BERT4Rec
export_recs_bulk(bulk_recommend_bert4rec_joint('books'), idx2item_joint, f'{AB_TEST_DIR}/bert_multi_books_recs_bulk.json')
export_recs_bulk(bulk_recommend_bert4rec_joint('movies'), idx2item_joint, f'{AB_TEST_DIR}/bert_multi_movies_recs_bulk.json')

# Single-domain BERT4Rec -- same user coverage as the domain-filtered sequences
# used to train each model, so they line up with the joint model's recs per-user
export_recs_bulk(bulk_recommend_bert4rec_single_domain(books_only_bundle), idx2item_books_only, f'{AB_TEST_DIR}/bert_single_books_recs_bulk.json')
export_recs_bulk(bulk_recommend_bert4rec_single_domain(movies_only_bundle), idx2item_movies_only, f'{AB_TEST_DIR}/bert_single_movies_recs_bulk.json')

Saved 127188 users' recs to /content/drive/MyDrive/recsys-data/a-b-test/bert_multi_books_recs_bulk.json
Saved 127188 users' recs to /content/drive/MyDrive/recsys-data/a-b-test/bert_multi_movies_recs_bulk.json
Saved 126384 users' recs to /content/drive/MyDrive/recsys-data/a-b-test/bert_single_books_recs_bulk.json
Saved 127152 users' recs to /content/drive/MyDrive/recsys-data/a-b-test/bert_single_movies_recs_bulk.json

[{'user_id': 'AE22236AFRRSMQIKGG7TPTB75QEA',
  'recommended_item_ids': ['movies::B00G5G7K7O',
   'movies::B00AZMFK3K',
   'movies::B00A7OIXW6',
   'movies::B0083SBJXS',
   'movies::B004G600A4',
   'movies::B004G6009K',
   'movies::B008JFUPK8',
   'movies::B002ZG97Z6',
   'movies::B008JFUR10',
   'movies::B004LWZWGK'],
  'recommended_titles': ['Frozen (Feature) [Blu-ray]',
   'Star Trek Into Darkness',
   'Wreck-It Ralph (Two-Disc Blu-ray/DVD Combo)',
   "Marvel's The Avengers [Blu-ray]",
   'Tangled',
   'Tangled (Four-Disc Combo: Blu-ray 3D / Blu-ray / DVD / Digital Copy) [3D Blu-ray]',
   'Man of Steel (Blu-ray)',
   'How to Train Your Dragon (Two-Disc Blu-ray/DVD Combo)',
   'Pacific Rim [Blu-ray]',
   'The Dark Knight Rises [Blu-ray]']},
 {'user_id': 'AE222H3FGXWLHRFUMGMS2RR57NDQ',
  'recommended_item_ids': ['movies::B0776JGNYG',
   'movies::B07JJ6HPS9',
   'movies::B01LTHMWRG',
   'movies::B07XVFMQK4',
   'movies::B077R32LVQ',
   'movies::B07B64T9B3',
   'movies::B072148H97',
   'movies::B081F2T9QJ',
   'movies::B077R4K3SK',
   'movies::B07KLS2X4F'],
  'recommended_titles': ['The Big Bang Theory: The Complete Eleventh Season (DVD)',
   'The Big Bang Theory: The Twelfth and Final Season [DVD]',
   'The Big Bang Theory: The Complete Tenth Season [DVD]',
   'Downton Abbey Movie, 2019',
   'The Greatest Showman',
   'The Office: The Complete Series',
   'NCIS: The Fourteenth Season',
   nan,
   'Outlander: Season 3 [Blu-ray]',
   'Fantastic Beasts: The Crimes of Grindelwald (DVD)']},
 {'user_id': 'AE225P7FIMCUQD3TPAOF5LSGCLYQ',
  'recommended_item_ids': ['movies::B079FLYB41',
   'movies::B073RVFNV2',
   'movies::B01DUHOVAO',
   'movies::B01BLS9EVA',
   'movies::B071NDY4B2',
   'movies::B0721QYGSQ',
   'movies::B071LFWN4C',
   'movies::B07B16NSK6',
   'movies::B00WBJSOEC',
   'movies::B000RIWAVW'],
  'recommended_titles': ['Black Panther',
   'Spider-Man: Homecoming',
   'Gods Of Egypt',
   'Deadpool',
   'Alien: Covenant',
   'War For The Planet Of The Apes',
   'KONG: SKULL ISLAND: SE',
   'Winchester',
   'Men in Black (1997) / Men in Black II - Vol / Men in Black 3 - Set',
   'Halloween']},
 {'user_id': 'AE225Z2VRWT6GPTOMA4H4O3H2KVQ',
  'recommended_item_ids': ['movies::B0045HCJSA',
   'movies::B0001I55U6',
   'movies::0767817478',
   'movies::B002ZG99KO',
   'movies::B000083C6R',
   'movies::B000063US5',
   'movies::B005GPFZEK',
   'movies::B00BEIYMAG',
   'movies::B003Q6D2B4',
   'movies::B0053TWV5K'],
  'recommended_titles': ['The Time Machine [DVD]',
   'SOMETHING WICKED THIS WAY COMES',
   'Godzilla',
   "The Sorcerer's Apprentice",
   'The Ghost and Mrs. Muir',
   'Lions Gate, Rose Red',
   "Don't Be Afraid of the Dark (Remastered, Special Edition)",
   'The Conjuring (DVD)',
   'Red (Special Edition)',
   'Elvira: Mistress of the Dark']},
 {'user_id': 'AE226GVVDBQEUWO4CWCXRJ3TKHAA',
  'recommended_item_ids': ['movies::B073RPZK88',
   'movies::B07M5HWD5J',
   'movies::B07FMHTRFD',
   'movies::B07CQ865WW',
   'movies::B07FNZ35DV',
   'movies::B07RZVZ6X3',
   'movies::B07V3TNS85',
   'movies::B07G9LGZCM',
   'movies::B07WSR1Q6R',
   'movies::B06VYH1GF7'],
  'recommended_titles': [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]},
 {'user_id': 'AE22AJP4C4JP57LVR5BBHC3RJAWA',
  'recommended_item_ids': ['movies::B00G5G7K7O',
   'movies::B000W91RUG',
   'movies::B00N1JQ2UO',
   'movies::B000NQRE1E',
   'movies::B005LAII08',
   'movies::B005S9EKCW',
   'movies::B005OCFHHK',
   'movies::B001E5CH0G',
   'movies::B004G6009U',
   'movies::B0036TGT3E'],
  'recommended_titles': ['Frozen (Feature) [Blu-ray]',
   'The Big Bang Theory: Season 1',
   'Guardians Of The Galaxy',
   'Titanic (Four-Disc Combo: Blu-ray / DVD / Digital Copy)',
   'Brave',
   'Les Misérables (2012) [Blu-ray]',
   'Harry Potter: Complete 8-Film Collection',
   'Elf (Blu-ray)',
   'Tangled (Two-Disc Blu-ray/DVD Combo)',
   'Lion King (Diamond Edition)']},
 {'user_id': 'AE22BZ4I2434QRWLOQ52XURGWREA',
  'recommended_item_ids': ['movies::B081W544J7',
   'movies::B07KFRF1X5',
   'movies::B07FMHTRFD',
   'movies::B07K2KJQB9',
   'movies::B078HLD83H',
   'movies::B01M2C4NP8',
   'movies::B06Y1H48K7',
   'movies::B07PPK1BXZ',
   'movies::B072J84141',
   'movies::B07BYJX9FZ'],
  'recommended_titles': [nan,
   nan,
   nan,
   'Bohemian Rhapsody',
   'The Shape of Water',
   'Arrival',
   'Get Out',
   'Aquaman',
   nan,
   nan]},
 {'user_id': 'AE22CFXT3QZKUQJORVTGL3VQXAAA',
  'recommended_item_ids': ['movies::B07PPK1BXZ',
   'movies::B07KFRF1X5',
   'movies::B097YYZ87F',
   'movies::B07816TG17',
   'movies::B07CYQT4F1',
   'movies::B07PPR5Q4S',
   'movies::B078HT6H7K',
   'movies::B01MY5P3F0',
   'movies::B075SMMR8B',
   'movies::B073RPZK88'],
  'recommended_titles': ['Aquaman',
   nan,
   nan,
   nan,
   nan,
   nan,
   nan,
   nan,
   nan,
   nan]},
 {'user_id': 'AE22ERJ7YI3QH427LG2TSMGI6XAA',
  'recommended_item_ids': ['movies::B07DKY35N5',
   'movies::B074TR63JC',
   'movies::B07KLFM6Q3',
   'movies::B005BYBZKY',
   'movies::B076M4XM6H',
   'movies::B01KYRX23U',
   'movies::B07VLJ9KB6',
   'movies::B003NOGNQU',
   'movies::B07DPFG4S6',
   'movies::B0062KMDWU'],
  'recommended_titles': ['Universal Classic Monsters: Complete 30-Film Collection',
   'The Old Dark House [Blu-ray]',
   'Horror of Dracula (1958) [Blu-ray]',
   'Laurel & Hardy: The Essential Collection',
   'Twin Peaks: A Limited Event Series [Blu-ray]',
   'Batman: Return of the Caped Crusaders [Blu-ray]',
   'Godzilla, the Showa-Era Films, 1954–1975 (The Criterion Collection) [Blu-ray]',
   'Thriller: The Complete Series',
   'Thelma Todd & Zasu Pitts: The Hal Roach Collection 1931-33',
   'The Mr. Magoo: Theatrical Collection']},
 {'user_id': 'AE22FRSQXOAUGKWFU4DS6CMUF76A',
  'recommended_item_ids': ['movies::B00004W46I',
   'movies::B000065V3P',
   'movies::B00003CXRM',
   'movies::B000VBJEEG',
   'movies::B0002F6BRE',
   'movies::B0000549B0',
   'movies::6304765266',
   'movies::6305428042',
   'movies::6305236569',
   'movies::B0000AQS0F'],
  'recommended_titles': ["Somewhere in Time (Collector's Edition)",
   'Captain Ron',
   'O Brother, Where Art Thou?',
   'Ratatouille',
   'Elf (DVD)',
   'Harvey',
   'While You Were Sleeping',
   'Buena Vista Home Video, Hocus Pocus',
   'Overboard',
   'Firefly: The Complete Series']},
 {'user_id': 'AE22G2FY634XKAK7O6D6PHKCXDHA',
  'recommended_item_ids': ['movies::B01LQV2Z7M',
   'movies::B00DNLZOCC',
   'movies::B07379KS9H',
   'movies::B00LOCLBVU',
   'movies::B002AL2TYC',
   'movies::B0112HPVEY',
   'movies::B00S4YGWAQ',
   'movies::B00DNLZRLU',
   'movies::B018TNBX50',
   'movies::B015OVC1H4'],
  'recommended_titles': ['The Spirit of Christmas',
   'Hallmark Holiday Collection: Movie 4 Pack (Trading Christmas, Lucky Christmas, Case For Christmas, National Tree)',
   'A December Bride',
   'A Very Merry Mix-Up',
   'The Most Wonderful Time of the Year',
   "Christmas at Cartwright's",
   'Signed, Sealed, Delivered: The Complete Series (Hallmark)',
   'Holiday Romance Collection Movie 10 Pack',
   'Crown for Christmas',
   'Let It Snow']},
 {'user_id': 'AE22J4D76YM6ZBBRSUKCIK5BRJLQ',
  'recommended_item_ids': ['movies::B01MRNUJUO',
   'movies::B0779FK899',
   'movies::B01LZ9CO60',
   'movies::B003MAQ31A',
   'movies::B01N0AEYU6',
   'movies::B01CIV3YBA',
   'movies::B00J2PFPVI',
   'movies::B01N1P87AZ',
   'movies::B006S08FUS',
   'movies::B003LFG33O'],
  'recommended_titles': [nan,
   nan,
   nan,
   nan,
   nan,
   nan,
   'Frozen',
   nan,
   nan,
   'Avatar']},
 {'user_id': 'AE22JLAQRRZQVNLTCQY6CWRAYVHA',
  'recommended_item_ids': ['movies::B00J8CG6KE',
   'movies::B00HYTSTNU',
   'movies::B00TPJE3ZK',
   'movies::B00HAQAQME',
   'movies::B00I8H6MGS',
   'movies::B00IRMTTPU',
   'movies::B00J8CGU64',
   'movies::B00KAU9JD4',
   'movies::B00IRMQADY',
   'movies::B00IMY9TNK'],
  'recommended_titles': [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]},
 {'user_id': 'AE22M3AD4AUAGF3RGOJTE7SIOXMQ',
  'recommended_item_ids': ['movies::B00SW92TN2',
   'movies::B00N9KD460',
   'movies::B008COIF94',
   'movies::B01LWX85X0',
   'movies::B00KB01NQO',
   'movies::B00AZMFO6I',
   'movies::B01IARNQJ6',
   'movies::B004D1T8B4',
   'movies::B008Y1YK0I',
   'movies::B008ODZEQ0'],
  'recommended_titles': ['Looney Tunes Musical Masterpieces (DVD)',
   'Calvary [Blu-ray]',
   'My Afternoons with Margueritte (English Subtitled)',
   nan,
   'The Railway Man',
   'Quartet',
   'Cafe Society',
   "Ken Burns: The National Parks - America's Best Idea",
   'Lawrence of Arabia (Restored Version) [Blu-ray]',
   nan]},
 {'user_id': 'AE22M4ZE4CYTIXJHYTGMHERX6B2Q',
  'recommended_item_ids': ['movies::B00X8UKOUK',
   'movies::B00RSGIVVO',
   'movies::B00I3MQNWG',
   'movies::B01AB17IGQ',
   'movies::B00CW8DRU8',
   'movies::B00I3MPZUW',
   'movies::B00PSLQYWE',
   'movies::B018GTUWPO',
   'movies::B00RSGHX3Q',
   'movies::B00BS4L6YG'],
  'recommended_titles': [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]},
 {'user_id': 'AE22M5CUEXPHVOEE5B5QEVVUVAYA',
  'recommended_item_ids': ['movies::B01H2JPTDO',
   'movies::B00KHWSB5M',
   'movies::B00VSG3L5G',
   'movies::B073ZQ3DZQ',
   'movies::B005OCFGTO',
   'movies::B00C8CQRQ4',
   'movies::B008CLI4N4',
   'movies::B01LTHOAGC',
   'movies::B00N1JQ452',
   'movies::B018FK66TU'],
  'recommended_titles': ['Game of Thrones: The Complete 6th Season [DVD]',
   'Game of Thrones: Season 4',
   'Game of Thrones: Season 5',
   'Game Of Thrones: Season 7 (C&R/DVD+DC)',
   'Harry Potter: The Complete 8-Film Collection [DVD]',
   'Game of Thrones: Season 3',
   'Game of Thrones: Season 1',
   'Fantastic Beasts and Where to Find Them (DVD)',
   'Guardians of the Galaxy',
   'Star Wars: The Force Awakens']},
 {'user_id': 'AE22MKI7UCHLFE2ZLY24342RT76A',
  'recommended_item_ids': ['movies::B01EIM5SCU',
   'movies::B01J4SRJFW',
   'movies::B01J4SR91G',
   'movies::B01J4SST1K',
   'movies::B01MDTLXQN',
   'movies::B01MFF1O50',
   'movies::B01J4STKWC',
   'movies::B017AOY4WS',
   'movies::B01J4SS7NA',
   'movies::B01J4STMP2'],
  'recommended_titles': [nan,
   nan,
   nan,
   nan,
   nan,
   nan,
   'Goliath',
   nan,
   nan,
   nan]},
 {'user_id': 'AE22MQU5CGDMMUJEVJWT6APDZ6ZQ',
  'recommended_item_ids': ['movies::B07S5HX14T',
   'movies::B09F59CZ7R',
   'movies::B08VF7CR17',
   'movies::B093CNZ7ST',
   'movies::B08MMJTJSH',
   'movies::B07FMHTRFD',
   'movies::B07RZVZ6X3',
   'movies::B09ML1QV1S',
   'movies::B08QZN6LCM',
   'movies::B07V3TNS85'],
  'recommended_titles': [nan,
   nan,
   nan,
   'The Tomorrow War',
   nan,
   nan,
   nan,
   nan,
   nan,
   nan]},
 {'user_id': 'AE22NYNCFWZA4YTOO7CVMCCJQZZQ',
  'recommended_item_ids': ['movies::B01N47VPJG',
   'movies::B075K23YTM',
   'movies::B015WVHVEY',
   'movies::B0776JGNYG',
   'movies::B008RJ6TTC',
   'movies::B00KYCA4QY',
   'movies::B000096IAC',
   'movies::B000BOH8Y6',
   'movies::B0012E2F60',
   'movies::B01NAJ4HMI'],
  'recommended_titles': ['Star Trek: Deep Space Nine: The Complete Series',
   'The Orville: The Complete First Season',
   'The Big Bang Theory: Season 9 [DVD]',
   'The Big Bang Theory: The Complete Eleventh Season (DVD)',
   'Columbo: The Complete Series',
   'WKRP in Cincinnati: The Complete Series [DVD]',
   'The Final Countdown (Widescreen Edition)',
   'Alien Nation - The Complete Series',
   'Noble House [DVD]',
   'Star Trek: Voyager: The Complete Series']},
 {'user_id': 'AE22OAAUBBPYYGIWN3ZZGTQQI3LA',
  'recommended_item_ids': ['movies::B017AOY4WS',
   'movies::B01J4STMP2',
   'movies::B019YHGOZO',
   'movies::B00ZVS46AG',
   'movies::B019YHGMBK',
   'movies::B00A8P370M',
   'movies::B01GIIWVSG',
   'movies::B00ARCOHNW',
   'movies::B016Q1N8FK',
   'movies::B01EN8FBG2'],
  'recommended_titles': [nan,
   nan,
   nan,
   'The Age Of Adaline',
   nan,
   nan,
   nan,
   nan,
   'Room',
   nan]},
 {'user_id': 'AE22RP65USPRTIPUADYJRFOWCMHQ',
  'recommended_item_ids': ['movies::B0B3GQFVS6',
   'movies::B07KZGS6J9',
   'movies::B0B2Y8CDZL',
   'movies::B07QLB71HL',
   'movies::B09HJS6YKF',
   'movies::6317631093',
   'movies::B09LRX2TXR',
   'movies::B07J3B7DQ9',
   'movies::B07HSKPDBV',
   'movies::B07PDTXFCY'],
  'recommended_titles': ['Jurassic World Dominion - Blu-ray + DVD + Digital',
   'Mule, The (DVD)',
   'Jurassic World Dominion [DVD]',
   'John Wick: Chapter 3 – Parabellum',
   "No Time to Die (2021) - 2-Disc Collector's Edition [DVD]",
   'Aquaman (DVD)',
   'Spider-Man: No Way Home [Blu-ray]',
   'Halloween (2018) [Blu-ray]',
   'Venom [Blu-ray] [DVD]',
   'CAPTAIN MARVEL']},
 {'user_id': 'AE22RT3F2POKCGNHVHIJPP6MJMLA',
  'recommended_item_ids': ['movies::B07KFRF1X5',
   'movies::B082YJ8THX',
   'movies::B081W544J7',
   'movies::B07K2KJQB9',
   'movies::B07CYQT4F1',
   'movies::B07T6C9BQG',
   'movies::B07YLPGDV1',
   'movies::B07PPK1BXZ',
   'movies::B07XQLQK3J',
   'movies::B07M7XQSSY'],
  'recommended_titles': [nan,
   nan,
   nan,
   'Bohemian Rhapsody',
   nan,
   nan,
   nan,
   'Aquaman',
   nan,
   nan]},
 {'user_id': 'AE22RV5M6DBHQUC7A7WT3RAGH6LA',
  'recommended_item_ids': ['movies::B00CTNYLQA',
   'movies::B014TC618Y',
   'movies::B00G5G7EXY',
   'movies::B01I5JTBRU',
   'movies::B0042U94UQ',
   'movies::B00QUG7R9A',
   'movies::B00NYC73JW',
   'movies::B004HO6I4M',
   'movies::B001ILFUD2',
   'movies::B000065V42'],
  'recommended_titles': ['Robin Hood-40th Anniversary Edition (DVD + Digital Copy)',
   'Hotel Transylvania 2',
   'Frozen',
   'The Secret Life of Pets [DVD]',
   'Despicable Me',
   'Big Hero 6',
   'Minions [DVD]',
   'Rio',
   'Oliver and Company (20th Anniversary Edition)',
   'Honey, I Shrunk the Kids']},
 {'user_id': 'AE22SMQFML2VLYBHMX6HXPEE63VA',
  'recommended_item_ids': ['movies::B07KFRF1X5',
   'movies::B09K2DV8F3',
   'movies::B09MR83SXK',
   'movies::B084WGCT3Y',
   'movies::B08P7W4FL1',
   'movies::B081FJP1YN',
   'movies::B09Q21THBW',
   'movies::B081W544J7',
   'movies::B00366JI9O',
   'movies::B07XQLQK3J'],
  'recommended_titles': [nan,
   'No Time to Die',
   nan,
   nan,
   nan,
   nan,
   nan,
   nan,
   nan,
   nan]},
 {'user_id': 'AE22VHH4W6PWYTRHEMAP4U2N3CNQ',
  'recommended_item_ids': ['movies::B0000694WH',
   'movies::B003NOGNQU',
   'movies::B00009NHC0',
   'movies::B00518A70E',
   'movies::B000KRNGNG',
   'movies::B00065GX64',
   'movies::B0001HAGTW',
   'movies::B00000ILEU',
   'movies::B00005R1O7',
   'movies::B000BQ5IXW'],
  'recommended_titles': ['Curse of the Demon / Night of the Demon (Double Feature)',
   'Thriller: The Complete Series',
   'The Thing from Another World',
   'The Incredible Shrinking Man',
   'Green for Danger (The Criterion Collection) [DVD]',
   'M (The Criterion Collection)',
   "Mystery Classics - 50 Movie Pack: Algiers - Bulldog Drummond Escapes - Dick Tracy Meets Gruesome - The Man on the Eiffel Tower - Mr. Moto's Last Warning + 45 more!",
   'The Old Dark House',
   'The Crawling Eye (Widescreen European Edition)',
   'Dark Crimes - 50 Movie Set: Flowers from a Stranger - The Limping Man - The Mystery of Mr. Wong - The Strange Woman - Whistle Stop - D.O.A. + 44 more!']},
 {'user_id': 'AE22VUHAULDBEBMUG2NGQRUHGNZQ',
  'recommended_item_ids': ['movies::B07PPK1BXZ',
   'movies::B07KFRF1X5',
   'movies::B01NC38QE1',
   'movies::B07816TG17',
   'movies::B076R18XTD',
   'movies::B07SNS9D3G',
   'movies::B01MY5P3F0',
   'movies::B082YJ8THX',
   'movies::B079NT73VP',
   'movies::B07K2KJQB9'],
  'recommended_titles': ['Aquaman',
   nan,
   nan,
   nan,
   nan,
   nan,
   nan,
   nan,
   nan,
   'Bohemian Rhapsody']},
 {'user_id': 'AE22VWZW3S6ERTPEGWHMHPZMA4WQ',
  'recommended_item_ids': ['movies::B093CNZ7ST',
   'movies::B08QZN6LCM',
   'movies::B08VF7CR17',
   'movies::B07T8K9YSH',
   'movies::B084JFRR62',
   'movies::B09F59CZ7R',
   'movies::B07S5HX14T',
   'movies::B095RR8QYD',
   'movies::B07YLP14JH',
   'movies::B07DHYSBJ7'],
  'recommended_titles': ['The Tomorrow War',
   nan,
   nan,
   nan,
   nan,
   nan,
   nan,
   nan,
   nan,
   nan]},
 {'user_id': 'AE22XP7SWEM7CDRXMTLO2RLLCZ4A',
  'recommended_item_ids': ['movies::B014TC618Y',
   'movies::B018WXLHFI',
   'movies::B0034G4OYA',
   'movies::B00QUG7R9A',
   'movies::B00HCR8VEQ',
   'movies::B00N1JQ452',
   'movies::B00CHVJODE',
   'movies::B00FLAL3BO',
   'movies::B00P8KCZP0',
   'movies::B00YY3NV64'],
  'recommended_titles': ['Hotel Transylvania 2',
   'PEANUTS MOVIE, THE',
   'Hotel Transylvania',
   'Big Hero 6',
   'Scooby-Doo! Wrestlmania Mystery (DVD)',
   'Guardians of the Galaxy',
   'The Croods',
   'Dragons: Defenders of Berk Part 1',
   'Tinker Bell and the Legend of the Neverbeast',
   'Star Wars Rebels: Complete Season One']},
 {'user_id': 'AE22YYRSKXRL4JGWICZMDGFQSQBA',
  'recommended_item_ids': ['movies::B07DHYSBJ7',
   'movies::B072Z62L22',
   'movies::B01LWN5RHK',
   'movies::B07BYJX9FZ',
   'movies::B07FMHTRFD',
   'movies::B07CHQBF2R',
   'movies::B07BNSQ75X',
   'movies::B07RZVZ6X3',
   'movies::B07CQ865WW',
   'movies::B017PU3T7S'],
  'recommended_titles': [nan,
   nan,
   nan,
   nan,
   nan,
   nan,
   nan,
   nan,
   nan,
   'Altered Minds']},
 {'user_id': 'AE2324DZTYWS3LKNTEKJJZYHSQXQ',
  'recommended_item_ids': ['movies::B001P5HRMI',
   'movies::B00133KFGW',
   'movies::B00005JO9J',
   'movies::B000YABYLA',
   'movies::B000MQC9H4',
   'movies::B000YAA68C',
   'movies::B001FB4W0W',
   'movies::B002TYZKIM',
   'movies::B000N6TYLW',
   'movies::B000YAA2SQ'],
  'recommended_titles': ['Twilight (Two-Disc Special Edition)',
   'August Rush',
   "Grey's Anatomy: Season 1",
   'Juno (Single-Disc Edition)',
   'The Holiday',
   'P.S. I Love You',
   'True Blood: Season 1',
   "Michael Jackson's This Is It",
   'Gilmore Girls: Season 7',
   'Pushing Daisies: Season 1']},
 {'user_id': 'AE2326DGXXADKQXHAAMB72QODIJQ',
  'recommended_item_ids': ['movies::B07V3TNS85',
   'movies::B093CNZ7ST',
   'movies::B07FMHTRFD',
   'movies::B07RZVZ6X3',
   'movies::B07YL9WK1S',
   'movies::B073RPZK88',
   'movies::B07BYJX9FZ',
   'movies::B08VF7CR17',
   'movies::B07M5HWD5J',
   'movies::B081W544J7'],
  'recommended_titles': [nan,
   'The Tomorrow War',
   nan,
   nan,
   nan,
   nan,
   nan,
   nan,
   nan,
   nan]},
 {'user_id': 'AE232LDM3Q2PKC4GJA3Q3NTJFG5Q',
  'recommended_item_ids': ['movies::B01J4STKWC',
   'movies::B01J4SRJFW',
   'movies::B01EIM5SCU',
   'movies::B00Z620OVW',
   'movies::B076R18XTD',
   'movies::B01LWY8995',
   'movies::B01MDMGUMY',
   'movies::B017TDYLEQ',
   'movies::B07KFRF1X5',
   'movies::B01MDTLXQN'],
  'recommended_titles': ['Goliath',
   nan,
   nan,
   nan,
   nan,
   nan,
   nan,
   nan,
   nan,
   nan]},
 {'user_id': 'AE233JB2TE3MWX2DXWKNMEPO4NBA',
  'recommended_item_ids': ['movies::B09QH1952Z',
   'movies::B09KC1KYZX',
   'movies::B09LZ4W4YX',
   'movies::B09238VQ81',
   'movies::B09HP9C1T6',
   'movies::B07S3XSZ94',
   'movies::B09K2DV8F3',
   'movies::B08XP4KH56',
   'movies::B081FJP1YN',
   'movies::B07PPK1BXZ'],
  'recommended_titles': [nan,
   nan,
   nan,
   'Nobody',
   nan,
   nan,
   'No Time to Die',
   nan,
   nan,
   'Aquaman']},
 {'user_id': 'AE234DDQ2R3J7RSFM5INLLVGB3EA',
  'recommended_item_ids': ['movies::B01J4SRJFW',
   'movies::B01IS2RDJ2',
   'movies::B00YBX664Q',
   'movies::B01J4STKWC',
   'movies::B01EIM5SCU',
   'movies::B01J4SR91G',
   'movies::B01IS2PWV8',
   'movies::B01IS2LXBG',
   'movies::B017HYSNWI',
   'movies::B01MDTLXQN'],
  'recommended_titles': [nan,
   'The Man in the High Castle',
   nan,
   'Goliath',
   nan,
   nan,
   nan,
   nan,
   nan,
   nan]},
 {'user_id': 'AE234HSIDLMC66RLVRLAYRO2AKCQ',
  'recommended_item_ids': ['movies::B07SRF34CC',
   'movies::B07GW2ZW5K',
   'movies::B07HSKPDBV',
   'movies::B07PDTXFCY',
   'movies::6317632464',
   'movies::B07QXMVMKC',
   'movies::B09LGV8ZBN',
   'movies::B07DQ3ZWYS',
   'movies::B07VJWXSKM',
   'movies::B07RX2JVBQ'],
  'recommended_titles': ['Spider-Man: Far from Home',
   'Aquaman (Blu-ray)',
   'Venom [Blu-ray] [DVD]',
   'CAPTAIN MARVEL',
   'Spider-Man: Into the Spider-Verse [Blu-ray]',
   nan,
   'Ghostbusters: Afterlife [Blu-ray]',
   'Jurassic World: Fallen Kingdom',